<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ItemSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $items = [
            'name' => 'Allguard - W/C - 20Ltr ', 'price' => 24532, 'unit_id' => 'Pcs',
            'name' => 'Allguard - W/C - 10Ltr ', 'price' => 12474, 'unit_id' => 'Pcs',
            'name' => 'Allguard - W/C - 4Ltr', 'price' => 5229, 'unit_id' => 'Pcs',
            'name' => 'Allguard - W/C - 1Ltr', 'price' => 1358, 'unit_id' => 'Pcs',
            'name' => 'Bison Acrylic Emulsion - 20Ltr', 'price' => 8689, 'unit_id' => 'Pcs',
            'name' => 'Bison Acrylic Emulsion - 10Ltr', 'price' => 4513, 'unit_id' => 'Pcs',
            'name' => 'Bison Acrylic Emulsion - 4Ltr', 'price' => 1891, 'unit_id' => 'Pcs',
            'name' => 'Bison Acrylic Emulsion - 1Ltr', 'price' => 547, 'unit_id' => 'Pcs',
            'name' => 'Brolac Enamel - 4Ltr-LeafBrown', 'price' => 3752, 'unit_id' => 'Pcs',
            'name' => 'Brolac Enamel - 1Ltr-LeafBrown', 'price' => 974, 'unit_id' => 'Pcs',
            'name' => 'Brolac Enamel - 0.5Ltr-LeafBrown', 'price' => 513, 'unit_id' => 'Pcs',
            'name' => 'Brolac Enamel - 4Ltr Gr2', 'price' => 4102, 'unit_id' => 'Pcs',
            'name' => 'Brolac Enamel - 1Ltr Gr2', 'price' => 1079, 'unit_id' => 'Pcs',
            'name' => 'Brolac Enamel - 0.5Ltr Gr2', 'price' => 553, 'unit_id' => 'Pcs',
            'name' => 'Brolac Enamel - 4Ltr-White', 'price' => 4229, 'unit_id' => 'Pcs',
            'name' => 'Brolac Enamel - 1Ltr-White', 'price' => 1092, 'unit_id' => 'Pcs',
            'name' => 'Brolac Enamel - 0.5Ltr-White', 'price' => 566, 'unit_id' => 'Pcs',
            'name' => 'Cpvc Pipe SDR11 - 2""- R', 'price' => 4806, 'unit_id' => 'Pcs',
            'name' => 'Cpvc Pipe SDR11 - 1.1/2""- R', 'price' => 2884, 'unit_id' => 'Pcs',
            'name' => 'Cpvc Pipe SDR11 - 1.1/4""- R', 'price' => 2104, 'unit_id' => 'Pcs',
            'name' => 'Cpvc Pipe SDR11 - 1""- R', 'price' => 1321, 'unit_id' => 'Pcs',
            'name' => 'Cpvc Pipe SDR11 - 3/4""- R', 'price' => 850, 'unit_id' => 'Pcs',
            'name' => 'Cpvc Pipe SDR11 - 1/2""- R', 'price' => 584, 'unit_id' => 'Pcs',
            'name' => 'Cpvc Elbow - 2""', 'price' => 763, 'unit_id' => 'Pcs',
            'name' => 'Cpvc Elbow - 1.1/2""', 'price' => 391, 'unit_id' => 'Pcs',
            'name' => 'Cpvc Elbow - 1.1/4""', 'price' => 206, 'unit_id' => 'Pcs',
            'name' => 'Cpvc Elbow - 1""', 'price' => 92, 'unit_id' => 'Pcs',
            'name' => 'Cpvc Elbow - 3/4""', 'price' => 44, 'unit_id' => 'Pcs',
            'name' => 'Cpvc Elbow - 1/2""', 'price' => 41, 'unit_id' => 'Pcs',
            'name' => 'Cpvc Elbow 45 - 2""', 'price' => 790, 'unit_id' => 'Pcs',
            'name' => 'Cpvc Elbow 45 - 1.1/2""', 'price' => 400, 'unit_id' => 'Pcs',
            'name' => 'Cpvc Elbow 45 - 1.1/4""', 'price' => 242, 'unit_id' => 'Pcs',
            'name' => 'Cpvc Elbow 45 - 1""', 'price' => 117, 'unit_id' => 'Pcs',
            'name' => 'Cpvc Elbow 45- 3/4""', 'price' => 66, 'unit_id' => 'Pcs',
            'name' => 'Cpvc Elbow 45 - 1/2""', 'price' => 45, 'unit_id' => 'Pcs',
            'name' => 'Cpvc Socket - 2""', 'price' => 484, 'unit_id' => 'Pcs',
            'name' => 'Cpvc Socket - 1.1/2""', 'price' => 232, 'unit_id' => 'Pcs',
            'name' => 'Cpvc Socket - 1.1/4""', 'price' => 128, 'unit_id' => 'Pcs',
            'name' => 'Cpvc Socket - 1""', 'price' => 63, 'unit_id' => 'Pcs',
            'name' => 'Cpvc Socket - 3/4""', 'price' => 38, 'unit_id' => 'Pcs',
            'name' => 'Cpvc Socket - 1/2""', 'price' => 31, 'unit_id' => 'Pcs',
            'name' => 'Cpvc Tee - 2""', 'price' => 981, 'unit_id' => 'Pcs',
            'name' => 'Cpvc Tee - 1.1/2""', 'price' => 467, 'unit_id' => 'Pcs',
            'name' => 'Cpvc Tee - 1.1/4""', 'price' => 258, 'unit_id' => 'Pcs',
            'name' => 'Cpvc Tee - 1""', 'price' => 117, 'unit_id' => 'Pcs',
            'name' => 'Cpvc Tee - 3/4""', 'price' => 76, 'unit_id' => 'Pcs',
            'name' => 'Cpvc Tee - 1/2""', 'price' => 53, 'unit_id' => 'Pcs',
            'name' => 'Cpvc Ballvalve - 2""', 'price' => 3859, 'unit_id' => 'Pcs',
            'name' => 'Cpvc Ballvalve - 1.1/2""', 'price' => 2171, 'unit_id' => 'Pcs',
            'name' => 'Cpvc Ballvalve - 1.1/4""', 'price' => 1216, 'unit_id' => 'Pcs',
            'name' => 'Cpvc Ballvalve - 1""', 'price' => 760, 'unit_id' => 'Pcs',
            'name' => 'Cpvc Ballvalve - 3/4""', 'price' => 404, 'unit_id' => 'Pcs',
            'name' => 'Cpvc Ballvalve - 1/2""', 'price' => 246, 'unit_id' => 'Pcs',
            'name' => 'Cpvc Union - 2""', 'price' => 1227, 'unit_id' => 'Pcs',
            'name' => 'Cpvc Union - 1.1/2""', 'price' => 725, 'unit_id' => 'Pcs',
            'name' => 'Cpvc Union - 1.1/4""', 'price' => 423, 'unit_id' => 'Pcs',
            'name' => 'Cpvc Union - 1""', 'price' => 284, 'unit_id' => 'Pcs',
            'name' => 'Cpvc Union - 3/4""', 'price' => 209, 'unit_id' => 'Pcs',
            'name' => 'Cpvc Union - 1/2""', 'price' => 127, 'unit_id' => 'Pcs',
            'name' => 'Tiles 12*18 Prime-Richmond Lig.(6p)', 'price' => 75, 'unit_id' => 'Sqr/n',
            'name' => 'Tiles 12*18 Prime-Richmond Dk.(6p)', 'price' => 75, 'unit_id' => 'Sqr/n',
            'name' => 'Tiles 12*18 Prime-Richmond HL.(6p)', 'price' => 75, 'unit_id' => 'Sqr/n',
            'name' => 'Tiles 16*16 Nepovit-AtlasGrey (6p)', 'price' => 88, 'unit_id' => 'Sqr/n',
            'name' => 'Castic Soda', 'price' => 70, 'unit_id' => 'Pkt/n',
            'name' => 'Tarpin Oil - 700ml', 'price' => 110, 'unit_id' => 'Bot./n',
            'name' => 'Tarpin Oil - 400ml', 'price' => 90, 'unit_id' => 'Bot./n',
            'name' => 'Chalk Powder', 'price' => 20, 'unit_id' => 'Pkt/n',
            'name' => 'Brown', 'price' => 25, 'unit_id' => 'Pkt/n',
            'name' => 'Rose / Orange', 'price' => 25, 'unit_id' => 'Pkt/n',
            'name' => 'Cp Nipple 1""/ 1/2""', 'price' => 100, 'unit_id' => 'Pcs/n',
            'name' => 'Cp Nipple 2""', 'price' => 150, 'unit_id' => 'Pcs/n',
            'name' => 'Cp Nipple 1""- Viking', 'price' => 180, 'unit_id' => 'Pcs/n',
            'name' => 'Cp Nipple 2"" - Viking', 'price' => 250, 'unit_id' => 'Pcs/n',
            'name' => 'Cp Cap', 'price' => 25, 'unit_id' => 'Pcs/n',
            'name' => 'Khaxi Rol - 80/100/120', 'price' => 60, 'unit_id' => 'Mtr/n',
            'name' => 'Khaxi W/P -', 'price' => 25, 'unit_id' => 'Pcs/n',
            'name' => 'Khaxi Normal', 'price' => 5, 'unit_id' => 'Pcs/n',
            'name' => 'Putting Patta 8""', 'price' => 35, 'unit_id' => 'Pcs/n',
            'name' => 'Putting Patta 4""', 'price' => 15, 'unit_id' => 'Pcs/n',
            'name' => 'Roller 8""', 'price' => 250, 'unit_id' => 'Pcs/n',
            'name' => 'Roller 4""', 'price' => 150, 'unit_id' => 'Pcs/n',
            'name' => 'Brush 4""- 444', 'price' => 240, 'unit_id' => 'Pcs/n',
            'name' => 'Brush 3""- 444', 'price' => 180, 'unit_id' => 'Pcs/n',
            'name' => 'Brush 2""- 444', 'price' => 120, 'unit_id' => 'Pcs/n',
            'name' => 'Brush 1""- 444', 'price' => 60, 'unit_id' => 'Pcs/n',
            'name' => 'Brush 4""- 555', 'price' => 320, 'unit_id' => 'Pcs/n',
            'name' => 'Brush 3""- 555', 'price' => 240, 'unit_id' => 'Pcs/n',
            'name' => 'Brush 2""- 555', 'price' => 160, 'unit_id' => 'Pcs/n',
            'name' => 'Brush 1""- 555', 'price' => 80, 'unit_id' => 'Pcs/n',
            'name' => 'Brush - Pen', 'price' => 45, 'unit_id' => 'Pcs/n',
            'name' => 'Wall Putting', 'price' => 40, 'unit_id' => 'Kg/n',
            'name' => 'Wall Putting Bison 40kg', 'price' => 1250, 'unit_id' => 'Bag/n',
            'name' => 'Long Life - W/C - 20Ltr', 'price' => 35114, 'unit_id' => 'Pcs',
            'name' => 'Long Life - W/C - 10Ltr', 'price' => 17888, 'unit_id' => 'Pcs',
            'name' => 'Long Life - W/C - 4Ltr', 'price' => 7453, 'unit_id' => 'Pcs',
            'name' => 'Long Life - W/C - 1Ltr', 'price' => 1938, 'unit_id' => 'Pcs',
            'name' => 'Pvc Pipe 160mm-4kg-NS-3mtr', 'price' => 4290, 'unit_id' => 'Pcs',
            'name' => 'Pvc Pipe 110mm-4kg-NS-3mtr', 'price' => 1974, 'unit_id' => 'Pcs',
            'name' => 'Pvc Pipe 75mm-4kg-NS-3mtr', 'price' => 1023, 'unit_id' => 'Pcs',
            'name' => 'Pvc Pipe 160mm-4kg-ISI-3mtr-R', 'price' => 6210, 'unit_id' => 'Pcs',
            'name' => 'Pvc Pipe 110mm-4kg-ISI-3mtr-R', 'price' => 2135, 'unit_id' => 'Pcs',
            'name' => 'Pvc Pipe 160mm-6kg-NS-3mtr', 'price' => 6741, 'unit_id' => 'Pcs',
            'name' => 'Pvc Pipe 110mm-6kg-NS-3mtr', 'price' => 3033, 'unit_id' => 'Pcs',
            'name' => 'Pvc Pipe 50mm-6kg-NS-3mtr', 'price' => 612, 'unit_id' => 'Pcs',
            'name' => 'Pvc Pipe 50mm-6kg-ISI-3mtr-R', 'price' => 700, 'unit_id' => 'Pcs',
            'name' => 'Pvc Pipe 75mm4kg-ISI-3mtr-R', 'price' => 1070, 'unit_id' => 'Pcs',
            'name' => 'Pvc Bend - 160mm', 'price' => 1145, 'unit_id' => 'Pcs',
            'name' => 'Pvc Bend - 110mm', 'price' => 438, 'unit_id' => 'Pcs',
            'name' => 'Pvc Bend - 50mm', 'price' => 90, 'unit_id' => 'Pcs',
            'name' => 'Pvc Bend - 75mm', 'price' => 234, 'unit_id' => 'Pcs',
            'name' => 'Pvc Bend 45 - 160mm', 'price' => 885, 'unit_id' => 'Pcs',
            'name' => 'Pvc Bend 45 - 110mm', 'price' => 380, 'unit_id' => 'Pcs',
            'name' => 'Pvc Bend 45 - 75mm', 'price' => 180, 'unit_id' => 'Pcs',
            'name' => 'Pvc Bend 45 - 50mm', 'price' => 81, 'unit_id' => 'Pcs',
            'name' => 'Pvc Tee - 160mm', 'price' => 1470, 'unit_id' => 'Pcs',
            'name' => 'Pvc Tee - 110mm ', 'price' => 600, 'unit_id' => 'Pcs',
            'name' => 'Pvc Tee - 75mm', 'price' => 330, 'unit_id' => 'Pcs',
            'name' => 'Pvc Tee - 50mm', 'price' => 130, 'unit_id' => 'Pcs',
            'name' => 'Pvc Door Bend - 160mm', 'price' => 1257, 'unit_id' => 'Pcs',
            'name' => 'Pvc Door Bend - 110mm', 'price' => 545, 'unit_id' => 'Pcs',
            'name' => 'Pvc Door Bend - 75mm', 'price' => 290, 'unit_id' => 'Pcs',
            'name' => 'Pvc Door Tee - 160mm', 'price' => 1705, 'unit_id' => 'Pcs',
            'name' => 'Pvc Door Tee - 110mm', 'price' => 732, 'unit_id' => 'Pcs',
            'name' => 'Pvc Door Tee - 75mm', 'price' => 385, 'unit_id' => 'Pcs',
            'name' => 'Pvc Y-Tee - 160mm', 'price' => 2167, 'unit_id' => 'Pcs',
            'name' => 'Pvc Y-Tee - 110mm', 'price' => 715, 'unit_id' => 'Pcs',
            'name' => 'Pvc Y-Tee - 75mm', 'price' => 397, 'unit_id' => 'Pcs',
            'name' => 'Pvc MFT - 110*75mm', 'price' => 780, 'unit_id' => 'Pcs',
            'name' => 'Pvc N-Trap - 110*75mm', 'price' => 371, 'unit_id' => 'Pcs',
            'name' => 'Pvc R.Coupler - 110*75mm', 'price' => 274, 'unit_id' => 'Pcs',
            'name' => 'Pvc R.Coupler 75*50mm', 'price' => 130, 'unit_id' => 'Pcs',
            'name' => 'Pvc R.Coupler - 160*110mm', 'price' => 570, 'unit_id' => 'Pcs',
            'name' => 'Pvc R.Tee - 160*110mm', 'price' => 1352, 'unit_id' => 'Pcs',
            'name' => 'Pvc R.Tee - 110*75mm', 'price' => 503, 'unit_id' => 'Pcs',
            'name' => 'Pvc R.Y-Tee 110-75mm', 'price' => 634, 'unit_id' => 'Pcs',
            'name' => 'Pvc R.Y-Tee 160*110mm', 'price' => 3498, 'unit_id' => 'Pcs',
            'name' => 'Pvc Solvent - 250ml - R', 'price' => 355, 'unit_id' => 'Pcs',
            'name' => 'Pvc Solvent - 100ml - R ', 'price' => 230, 'unit_id' => 'Pcs',
            'name' => 'Pvc Solvent - 50ml - R', 'price' => 150, 'unit_id' => 'Pcs',
            'name' => 'Cpvc Flowgard - 237ml', 'price' => 931, 'unit_id' => 'Pcs',
            'name' => 'Cpvc Flowgard - 118ml', 'price' => 554, 'unit_id' => 'Pcs',
            'name' => 'Cpvc Flowgard - 59ml', 'price' => 380, 'unit_id' => 'Pcs',
            'name' => 'Cpvc Flowgard - 29.5ml', 'price' => 260, 'unit_id' => 'Pcs',
            'name' => 'Cpvc Flowgard - 15ml', 'price' => 184, 'unit_id' => 'Pcs',
            'name' => 'Pvc Couples - 160mm', 'price' => 737, 'unit_id' => 'Pcs',
            'name' => 'Pvc Couples - 110mm', 'price' => 321, 'unit_id' => 'Pcs',
            'name' => 'Pvc Couples - 75mm', 'price' => 190, 'unit_id' => 'Pcs',
            'name' => 'Pvc Clamp (Metal) - 160mm', 'price' => 224, 'unit_id' => 'Pcs',
            'name' => 'Pvc Clamp (Metal) - 110mm', 'price' => 110, 'unit_id' => 'Pcs',
            'name' => 'Pvc Clamp (Metal) - 75mm', 'price' => 85, 'unit_id' => 'Pcs',
            'name' => 'Pvc Clamp (Metal) - 50mm', 'price' => 65, 'unit_id' => 'Pcs',
            'name' => 'Pvc Clamp - 160mm', 'price' => 144, 'unit_id' => 'Pcs',
            'name' => 'Pvc Clamp - 110mm', 'price' => 78, 'unit_id' => 'Pcs',
            'name' => 'Pvc Clamp - 75mm', 'price' => 54, 'unit_id' => 'Pcs',
            'name' => 'Pvc Clamp - 50mm', 'price' => 44, 'unit_id' => 'Pcs',
            'name' => 'Pvc Square Jali ', 'price' => 214, 'unit_id' => 'Pcs',
            'name' => 'Pvc Lubricants - 100ml', 'price' => 87, 'unit_id' => 'Pcs',
            'name' => 'Pvc lubricants - 250ml', 'price' => 148, 'unit_id' => 'Pcs',
            'name' => 'Pvc Cross Tee - 110mm', 'price' => 729, 'unit_id' => 'Pcs',
            'name' => 'Pvc Cross Tee - 75mm', 'price' => 480, 'unit_id' => 'Pcs',
            'name' => 'Pvc Door Y-Tee - 160mm', 'price' => 2248, 'unit_id' => 'Pcs',
            'name' => 'Pvc Door Y-Tee - 110mm', 'price' => 921, 'unit_id' => 'Pcs',
            'name' => 'Pvc Door Y-Tee - 75mm', 'price' => 514, 'unit_id' => 'Pcs',
            'name' => 'Pvc P-Trap - 110mm', 'price' => 1005, 'unit_id' => 'Pcs',
            'name' => 'Pvc P-Trap - 75mm', 'price' => 609, 'unit_id' => 'Pcs',
            'name' => 'Pvc R.P-Trap - 110*75mm', 'price' => 1170, 'unit_id' => 'Pcs',
            'name' => 'Cpvc Tank Nipple - 2""', 'price' => 881, 'unit_id' => 'Pcs',
            'name' => 'Cpvc Tank Nipple - 1.1/2""', 'price' => 567, 'unit_id' => 'Pcs',
            'name' => 'Cpvc Tank Nipple - 1.1/4""', 'price' => 388, 'unit_id' => 'Pcs',
            'name' => 'Cpvc Tank Nipple - 1""', 'price' => 246, 'unit_id' => 'Pcs',
            'name' => 'Cpvc Tank Nipple - 3/4""', 'price' => 158, 'unit_id' => 'Pcs',
            'name' => 'Cpvc Tank Nipple - 1/2""', 'price' => 149, 'unit_id' => 'Pcs',
            'name' => 'Cpvc FAPT - 2""', 'price' => 535, 'unit_id' => 'Pcs',
            'name' => 'Cpvc FAPT - 1.1/2""', 'price' => 353, 'unit_id' => 'Pcs',
            'name' => 'Cpvc FAPT - 1.1/4""', 'price' => 251, 'unit_id' => 'Pcs',
            'name' => 'Cpvc FAPT - 1""', 'price' => 105, 'unit_id' => 'Pcs',
            'name' => 'Cpvc FAPT - 3/4""', 'price' => 70, 'unit_id' => 'Pcs',
            'name' => 'Cpvc FAPT - 1/2""', 'price' => 48, 'unit_id' => 'Pcs',
            'name' => 'Cpvc MAPT - 2""', 'price' => 395, 'unit_id' => 'Pcs',
            'name' => 'Cpvc MAPT - 1.1/2""', 'price' => 205, 'unit_id' => 'Pcs',
            'name' => 'Cpvc MAPT - 1.1/4""', 'price' => 140, 'unit_id' => 'Pcs',
            'name' => 'Cpvc MAPT - 1""', 'price' => 80, 'unit_id' => 'Pcs',
            'name' => 'Cpvc MAPT - 3/4""', 'price' => 53, 'unit_id' => 'Pcs',
            'name' => 'Cpvc MAPT - 1/2""', 'price' => 38, 'unit_id' => 'Pcs',
            'name' => 'Cpvc MABT - 2""', 'price' => 3650, 'unit_id' => 'Pcs',
            'name' => 'Cpvc MABT - 1.1/2""', 'price' => 1999, 'unit_id' => 'Pcs',
            'name' => 'Cpvc MABT - 1.1/4""', 'price' => 1581, 'unit_id' => 'Pcs',
            'name' => 'Cpvc MABT - 1""', 'price' => 767, 'unit_id' => 'Pcs',
            'name' => 'Cpvc MABT - 3/4""', 'price' => 507, 'unit_id' => 'Pcs',
            'name' => 'Cpvc MABT - 1/2""', 'price' => 377, 'unit_id' => 'Pcs',
            'name' => 'Cpvc FABT - 2""', 'price' => 3324, 'unit_id' => 'Pcs',
            'name' => 'Cpvc FABT - 1.1/2""', 'price' => 1855, 'unit_id' => 'Pcs',
            'name' => 'Cpvc FABT - 1.1/4""', 'price' => 1570, 'unit_id' => 'Pcs',
            'name' => 'Cpvc FABT - 1""', 'price' => 825, 'unit_id' => 'Pcs',
            'name' => 'Cpvc FABT - 3/4""', 'price' => 481, 'unit_id' => 'Pcs',
            'name' => 'Cpvc FABT - 1/2""', 'price' => 342, 'unit_id' => 'Pcs',
            'name' => 'Cpvc MABT - 3/4*1/2""', 'price' => 312, 'unit_id' => 'Pcs',
            'name' => 'Cpvc FABT - 3/4*1/2""', 'price' => 221, 'unit_id' => 'Pcs',
            'name' => 'Cpvc Step Over Bend - 1""', 'price' => 430, 'unit_id' => 'Pcs',
            'name' => 'Cpvc Step Over Bend - 3/4""', 'price' => 223, 'unit_id' => 'Pcs',
            'name' => 'Cpvc Step Over Bend - 1/2""', 'price' => 155, 'unit_id' => 'Pcs',
            'name' => 'Cpvc End Cap - 2""', 'price' => 344, 'unit_id' => 'Pcs',
            'name' => 'Cpvc End Cap - 1.1/2""', 'price' => 155, 'unit_id' => 'Pcs',
            'name' => 'Cpvc End Cap - 1.1/4""', 'price' => 106, 'unit_id' => 'Pcs',
            'name' => 'Cpvc End Cap - 1""', 'price' => 53, 'unit_id' => 'Pcs',
            'name' => 'Cpvc End Cap - 3/4""', 'price' => 33, 'unit_id' => 'Pcs',
            'name' => 'Cpvc End Cap - 1/2""', 'price' => 24, 'unit_id' => 'Pcs',
            'name' => 'Cpvc Cross Tee - 1""', 'price' => 256, 'unit_id' => 'Pcs',
            'name' => 'Cpvc Cross Tee - 3/4""', 'price' => 149, 'unit_id' => 'Pcs',
            'name' => 'Cpvc Cross Tee - 1/2""', 'price' => 73, 'unit_id' => 'Pcs',
            'name' => 'Cpvc Metal Clamp - 2""', 'price' => 43, 'unit_id' => 'Pcs',
            'name' => 'Cpvc Metal Clamp - 1.1/2""', 'price' => 38, 'unit_id' => 'Pcs',
            'name' => 'Cpvc Metal Clamp - 1.1/4""', 'price' => 36, 'unit_id' => 'Pcs',
            'name' => 'Cpvc Metal Clamp - 1""', 'price' => 28, 'unit_id' => 'Pcs',
            'name' => 'Cpvc Metal Clamp - 3/4""', 'price' => 25, 'unit_id' => 'Pcs',
            'name' => 'Cpvc Metal Clamp - 1/2""', 'price' => 19, 'unit_id' => 'Pcs',
            'name' => 'Cpvc Long Plug - 1/2""', 'price' => 23, 'unit_id' => 'Pcs',
            'name' => 'Cpvc Mixer Brs.Elbow 3/1 - 3/4*1/2""', 'price' => 984, 'unit_id' => 'Pcs',
            'name' => 'Cpvc mixer Brs.Elbow 2/1 - 3/4*1/2""', 'price' => 840, 'unit_id' => 'Pcs',
            'name' => 'Cpvc Brass Elbow - 3/4*1/2""', 'price' => 172, 'unit_id' => 'Pcs',
            'name' => 'Cpvc Brass Elbow - 1*1/2""', 'price' => 328, 'unit_id' => 'Pcs',
            'name' => 'Cpvc Brass Elbow - 1/2""', 'price' => 167, 'unit_id' => 'Pcs',
            'name' => 'Cpvc Brass Elbow - 3/4""', 'price' => 237, 'unit_id' => 'Pcs',
            'name' => 'Cpvc Brass Elbow - 1""', 'price' => 855, 'unit_id' => 'Pcs',
            'name' => 'Cpvc R.Socket - 2*1.1/2""', 'price' => 672, 'unit_id' => 'Pcs',
            'name' => 'Cpvc R.Socket - 2*1.1/4""', 'price' => 597, 'unit_id' => 'Pcs',
            'name' => 'Cpvc R.Socket - 2*1""', 'price' => 570, 'unit_id' => 'Pcs',
            'name' => 'Cpvc R.Socket - 2*3/4""', 'price' => 574, 'unit_id' => 'Pcs',
            'name' => 'Cpvc R.Socket - 2*1/2""', 'price' => 550, 'unit_id' => 'Pcs',
            'name' => 'Cpvc R.Socket - 1.1/2*1.1/4""', 'price' => 286, 'unit_id' => 'Pcs',
            'name' => 'Cpvc R.Socket - 1.1/2*1""', 'price' => 279, 'unit_id' => 'Pcs',
            'name' => 'Cpvc R.Socket - 1.1/2*3/4""', 'price' => 272, 'unit_id' => 'Pcs',
            'name' => 'Cpvc R.Socket - 1.1/2*1/2""', 'price' => 267, 'unit_id' => 'Pcs',
            'name' => 'Cpvc R.Socket - 1.1/4*1""', 'price' => 187, 'unit_id' => 'Pcs',
            'name' => 'Cpvc R.Socket - 1.1/4*3/4""', 'price' => 182, 'unit_id' => 'Pcs',
            'name' => 'Cpvc R.Socket - 1.1/4*1/2""', 'price' => 170, 'unit_id' => 'Pcs',
            'name' => 'Cpvc R.Socket - 1*3/4""', 'price' => 85, 'unit_id' => 'Pcs',
            'name' => 'Cpvc R.Socket - 1*1/2""', 'price' => 80, 'unit_id' => 'Pcs',
            'name' => 'Cpvc R.Socket - 3/4*1/2""', 'price' => 52, 'unit_id' => 'Pcs',
            'name' => 'Cpvc R.Tee - 2*1-1/2""', 'price' => 1110, 'unit_id' => 'Pcs',
            'name' => 'Cpvc R.Tee - 2*1-1/4""', 'price' => 1110, 'unit_id' => 'Pcs',
            'name' => 'Cpvc R.Tee - 2*1""', 'price' => 1110, 'unit_id' => 'Pcs',
            'name' => 'Cpvc R.Tee - 2*3/4""', 'price' => 1110, 'unit_id' => 'Pcs',
            'name' => 'Cpvc R.Tee - 2*1/2""', 'price' => 1025, 'unit_id' => 'Pcs',
            'name' => 'Cpvc R.Tee - 1.1/2*1.1/4""', 'price' => 540, 'unit_id' => 'Pcs',
            'name' => 'Cpvc R.Tee - 1.1/2*1""', 'price' => 544, 'unit_id' => 'Pcs',
            'name' => 'Cpvc R.Tee - 1.1/2*3/4""', 'price' => 581, 'unit_id' => 'Pcs',
            'name' => 'Cpvc R.Tee - 1.1/2*1/2""', 'price' => 584, 'unit_id' => 'Pcs',
            'name' => 'Cpvc R.Tee - 1.1/4*1""', 'price' => 411, 'unit_id' => 'Pcs',
            'name' => 'Cpvc R.Tee - 1.1/4*3/4""', 'price' => 411, 'unit_id' => 'Pcs',
            'name' => 'Cpvc R.Tee - 1.1/4*1/2""', 'price' => 3580, 'unit_id' => 'Pcs',
            'name' => 'Cpvc R.Tee - 1*3/4""', 'price' => 186, 'unit_id' => 'Pcs',
            'name' => 'Cpvc R.Tee - 1*1/2""', 'price' => 186, 'unit_id' => 'Pcs',
            'name' => 'Cpvc R.Tee - 3/4*1/2""', 'price' => 119, 'unit_id' => 'Pcs',
            'name' => 'Cpvc R.Bush - 2*1.1/2""', 'price' => 256, 'unit_id' => 'Pcs',
            'name' => 'Cpvc R.Bush - 2*1.1/4""', 'price' => 318, 'unit_id' => 'Pcs',
            'name' => 'Cpvc R.Bush - 2*1""', 'price' => 318, 'unit_id' => 'Pcs',
            'name' => 'Cpvc R.Bush - 2*3/4""', 'price' => 318, 'unit_id' => 'Pcs',
            'name' => 'Cpvc R.Bush - 2*1/2""', 'price' => 318, 'unit_id' => 'Pcs',
            'name' => 'Cpvc R.Bush - 1.1/2*1.1/4""', 'price' => 100, 'unit_id' => 'Pcs',
            'name' => 'Cpvc R.Bush - 1.1/2*1""', 'price' => 154, 'unit_id' => 'Pcs',
            'name' => 'Cpvc R.Bush - 1.1/2*3/4""', 'price' => 154, 'unit_id' => 'Pcs',
            'name' => 'Cpvc R.Bush - 1.1/2*1/2""', 'price' => 154, 'unit_id' => 'Pcs',
            'name' => 'Cpvc R.Bush - 1.1/4*1""', 'price' => 93, 'unit_id' => 'Pcs',
            'name' => 'Cpvc R.Bush - 1.1/4*3/4""', 'price' => 93, 'unit_id' => 'Pcs',
            'name' => 'Cpvc R.Bush - 1.1/4*1/2""', 'price' => 93, 'unit_id' => 'Pcs',
            'name' => 'Cpvc R.Bush - 1*3/4""', 'price' => 57, 'unit_id' => 'Pcs',
            'name' => 'Cpvc R.Bush - 1*1/2""', 'price' => 65, 'unit_id' => 'Pcs',
            'name' => 'Cpvc R.Bush - 3/4*1/2""', 'price' => 30, 'unit_id' => 'Pcs',
            'name' => 'Thinner - Lose', 'price' => 140, 'unit_id' => 'Bot./n',
            'name' => 'Thinner - Duco', 'price' => 450, 'unit_id' => 'Can/n',
            'name' => 'Easy Clean - 20ltr', 'price' => 19421, 'unit_id' => 'Pcs',
            'name' => 'Easy Clean - 10ltr', 'price' => 9859, 'unit_id' => 'Pcs',
            'name' => 'Easy Clean - 4ltr', 'price' => 4151, 'unit_id' => 'Pcs',
            'name' => 'Easy Clean - 1ltr', 'price' => 1070, 'unit_id' => 'Pcs',
            'name' => 'W/C Smooth - 20ltr', 'price' => 19517, 'unit_id' => 'Pcs',
            'name' => 'W/C Smooth - 10ltr', 'price' => 9919, 'unit_id' => 'Pcs',
            'name' => 'W/C Smooth - 4ltr', 'price' => 4215, 'unit_id' => 'Pcs',
            'name' => 'W/C Smooth - 1ltr', 'price' => 1107, 'unit_id' => 'Pcs',
            'name' => 'Walmasta Classic W/C - 20ltr', 'price' => 9570, 'unit_id' => 'Pcs',
            'name' => 'Walmasta Classic W/C - 10ltr', 'price' => 4962, 'unit_id' => 'Pcs',
            'name' => 'Walmasta Classic W/C - 4ltr', 'price' => 2151, 'unit_id' => 'Pcs',
            'name' => 'Walmasta Classic W/C - 1ltr', 'price' => 598, 'unit_id' => 'Pcs',
            'name' => 'Silk Breathe Easy - 20ltr', 'price' => 38948, 'unit_id' => 'Pcs',
            'name' => 'Silk Breathe Easy - 10ltr', 'price' => 19613, 'unit_id' => 'Pcs',
            'name' => 'Silk Breathe Easy - 4ltr', 'price' => 8235, 'unit_id' => 'Pcs',
            'name' => 'Silk Breathe Easy - 1ltr', 'price' => 2204, 'unit_id' => 'Pcs',
            'name' => 'Silk Luxury Emulsion - 20ltr', 'price' => 25227, 'unit_id' => 'Pcs',
            'name' => 'Silk Luxury Emulsion - 10ltr', 'price' => 12808, 'unit_id' => 'Pcs',
            'name' => 'Silk Luxury Emulsion - 4ltr', 'price' => 5395, 'unit_id' => 'Pcs',
            'name' => 'Silk Luxury Emulsion - 1ltr', 'price' => 1391, 'unit_id' => 'Pcs',
            'name' => 'Distemper - 20Kg', 'price' => 2200, 'unit_id' => 'Pcs/n',
            'name' => 'Distemper - 10Kg', 'price' => 1200, 'unit_id' => 'Pcs/n',
            'name' => 'Distemper - 5Kg', 'price' => 700, 'unit_id' => 'Pcs/n',
            'name' => 'Distemper - 1Kg', 'price' => 150, 'unit_id' => 'Pcs/n',
            'name' => 'Jensolin Cement Primer - 20ltr', 'price' => 4480, 'unit_id' => 'Pcs',
            'name' => 'Jensolin Cement Primer - 10ltr', 'price' => 2318, 'unit_id' => 'Pcs',
            'name' => 'Jensolin Cement Primer - 4ltr', 'price' => 1007, 'unit_id' => 'Pcs',
            'name' => 'Jensolin Cement Primer - 1ltr', 'price' => 280, 'unit_id' => 'Pcs',
            'name' => 'BP Exterior Primer - 20ltr', 'price' => 8240, 'unit_id' => 'Pcs',
            'name' => 'BP Exterior Primer - 10ltr', 'price' => 4154, 'unit_id' => 'Pcs',
            'name' => 'BP Exterior Primer - 4ltr', 'price' => 1753, 'unit_id' => 'Pcs',
            'name' => 'BP Exterior Primer - 1ltr', 'price' => 463, 'unit_id' => 'Pcs',
            'name' => 'BP Cement Primer - 20ltr', 'price' => 5999, 'unit_id' => 'Pcs',
            'name' => 'BP Cement Primer - 10ltr', 'price' => 3271, 'unit_id' => 'Pcs',
            'name' => 'BP Cement Primer - 4ltr', 'price' => 1418, 'unit_id' => 'Pcs',
            'name' => 'BP Cement Primer - 1ltr', 'price' => 403, 'unit_id' => 'Pcs',
            'name' => 'Advance Latex Plus - 20ltr', 'price' => 12691, 'unit_id' => 'Pcs',
            'name' => 'Advance Latex Plus - 5ltr', 'price' => 3300, 'unit_id' => 'Pcs',
            'name' => 'Advance Latex Plus - 1ltr', 'price' => 700, 'unit_id' => 'Pcs',
            'name' => 'W/C Exterior Primer - 20ltr', 'price' => 8882, 'unit_id' => 'Pcs',
            'name' => 'W/C Exterior Primer - 10ltr', 'price' => 4689, 'unit_id' => 'Pcs',
            'name' => 'W/C Exterior Primer - 4ltr', 'price' => 1964, 'unit_id' => 'Pcs',
            'name' => 'W/C Exterior Primer - 1ltr', 'price' => 562, 'unit_id' => 'Pcs',
            'name' => 'Red Oxide (Metal) Primer - 20ltr', 'price' => 9206, 'unit_id' => 'Pcs',
            'name' => 'Red Oxide (Metal) Primer - 4ltr', 'price' => 2008, 'unit_id' => 'Pcs',
            'name' => 'Red Oxide (Metal) Primer - 1ltr', 'price' => 544, 'unit_id' => 'Pcs',
            'name' => 'Red Oxide (Metal) Primer - 0.5ltr', 'price' => 301, 'unit_id' => 'Pcs',
            'name' => 'Wood Primer - 20ltr', 'price' => 11438, 'unit_id' => 'Pcs',
            'name' => 'Wood Primer - 4ltr', 'price' => 2510, 'unit_id' => 'Pcs',
            'name' => 'Wood Primer - 1ltr', 'price' => 670, 'unit_id' => 'Pcs',
            'name' => 'Wood Primer - 0.5ltr', 'price' => 372, 'unit_id' => 'Pcs',
            'name' => 'Aluminium Paint - 4ltr', 'price' => 3593, 'unit_id' => 'Pcs',
            'name' => 'Aluminium Paint - 1ltr', 'price' => 941, 'unit_id' => 'Pcs',
            'name' => 'Aluminium Paint - 0.5ltr', 'price' => 505, 'unit_id' => 'Pcs',
            'name' => 'Wood Keeper - 1ltr', 'price' => 776, 'unit_id' => 'Pcs',
            'name' => 'Single Set Commode -Jenson-A-150', 'price' => 12600, 'unit_id' => 'Set/n',
            'name' => 'Single Set Commode -Jenson-21425', 'price' => 26200, 'unit_id' => 'Set/n',
            'name' => 'Single Set Commode -Jenson-21025', 'price' => 25800, 'unit_id' => 'Set/n',
            'name' => 'Single Set Commode -Jenson-21987', 'price' => 16700, 'unit_id' => 'Set/n',
            'name' => 'Sink Mixer - Terovit-IG', 'price' => 7080, 'unit_id' => 'Set',
            'name' => 'Wast Pipe Coupling - Japper', 'price' => 200, 'unit_id' => 'Pcs/n',
            'name' => 'Wast Pipe NonCoupling - R', 'price' => 120, 'unit_id' => 'Pcs/n',
            'name' => 'Sink Coupling - H', 'price' => 350, 'unit_id' => 'Pcs/n',
            'name' => 'Connection Pipe 24"" SPL', 'price' => 180, 'unit_id' => 'Pcs/n',
            'name' => 'Connection Pipe 18"" SPL', 'price' => 170, 'unit_id' => 'Pcs/n',
            'name' => 'Towel Rod-Huk 24"" -  Buno', 'price' => 480, 'unit_id' => 'Pcs/n',
            'name' => 'Towel Rod-Huk 18"" -  Buno', 'price' => 450, 'unit_id' => 'Pcs/n',
            'name' => 'Towel Rod 24"" -  Cinder', 'price' => 650, 'unit_id' => 'Pcs/n',
            'name' => 'Angle Valve - Terovit-IG', 'price' => 1610, 'unit_id' => 'Pcs',
            'name' => 'Angle Valve - Terovit-SLK', 'price' => 1740, 'unit_id' => 'Pcs',
            'name' => 'Angle Valve 2 Way - Terovit-IG', 'price' => 2770, 'unit_id' => 'Pcs',
            'name' => 'Angle Valve 2 Way - Terovit-SLK', 'price' => 2770, 'unit_id' => 'Pcs',
            'name' => 'Angle Valve Uno - G5007A1', 'price' => 2010, 'unit_id' => 'Pcs',
            'name' => 'Haxo Blade', 'price' => 25, 'unit_id' => 'Pcs/n',
            'name' => 'Commod Spray - Tertovit', 'price' => 1200, 'unit_id' => 'Set/n',
            'name' => 'Commod Spray Slimline -E8354A1', 'price' => 2510, 'unit_id' => 'Set',
            'name' => 'M-Seal  100grm', 'price' => 80, 'unit_id' => 'Pcs/n',
            'name' => 'M-Seal  50grm', 'price' => 40, 'unit_id' => 'Pcs/n',
            'name' => 'White Cement - 1kg', 'price' => 50, 'unit_id' => 'Pkt/n',
            'name' => 'Orisha Pan - Stalo', 'price' => 1200, 'unit_id' => 'Set/n',
            'name' => 'Seltape - Polo', 'price' => 20, 'unit_id' => 'Pcs/n',
            'name' => 'Orisha Pan -500mm -C0133CS', 'price' => 3610, 'unit_id' => 'Pcs',
            'name' => 'Ceramic Syphon - Parryware', 'price' => 700, 'unit_id' => 'Pcs/n',
            'name' => 'Liquid Dispenser', 'price' => 1050, 'unit_id' => 'Pcs/n',
            'name' => 'Colour Mixing Charge', 'price' => 0, 'unit_id' => 'Ml/T',
            'name' => 'Parish', 'price' => 50, 'unit_id' => 'Pkt/n',
            'name' => 'Single Set Commode Cute -12""', 'price' => 21550, 'unit_id' => 'Set',
            'name' => 'Pvc Solvent - 50Ml - Normal', 'price' => 50, 'unit_id' => 'Pcs/n',
            'name' => 'Pvc Solvent - 100ml - normal', 'price' => 100, 'unit_id' => 'Pcs/n',
            'name' => 'Wall Mixer 2/1 Uno - G5016A1', 'price' => 10630, 'unit_id' => 'Set',
            'name' => 'Wall Mixer 2/1 Praseo - G5816A1', 'price' => 11490, 'unit_id' => 'Set',
            'name' => 'Wall Mixer 2/1 AgatPro - G3316A1', 'price' => 14830, 'unit_id' => 'Set',
            'name' => 'Wall Mixer Parryware - Droplet', 'price' => 11320, 'unit_id' => 'Set',
            'name' => 'Wall Mixer - Terovit - SLK', 'price' => 8580, 'unit_id' => 'Set',
            'name' => 'Wall Mixer - Terovit - IG', 'price' => 8550, 'unit_id' => 'Set',
            'name' => 'Wall Mixer - Terovit - Fusion', 'price' => 9720, 'unit_id' => 'Set',
            'name' => 'Basin Mixer S/L - Uno - T5065A1', 'price' => 7210, 'unit_id' => 'Set',
            'name' => 'Basin Mixer S/L- AgatPro - G3314A1', 'price' => 9830, 'unit_id' => 'Set',
            'name' => 'Basin Mixer S/L- Praseo - G5814A1', 'price' => 7370, 'unit_id' => 'Set',
            'name' => 'Basin Mixer C/H - Uno - T5015A1', 'price' => 7050, 'unit_id' => 'Set',
            'name' => 'Basin Mixer C/H-Parryware-Droplat', 'price' => 7170, 'unit_id' => 'Set',
            'name' => 'Basin Mixer S/L-Terovit-Fusion', 'price' => 9210, 'unit_id' => 'Set',
            'name' => 'Basin Mixer C/H-Terovit - Slk', 'price' => 6620, 'unit_id' => 'Set',
            'name' => 'Basin Mixer C/H-Terovit - IG', 'price' => 5660, 'unit_id' => 'Set',
            'name' => 'Bib Cock Uno - G5004A1', 'price' => 2160, 'unit_id' => 'Pcs',
            'name' => 'Bib Cock Parryware -Droplat', 'price' => 2630, 'unit_id' => 'Pcs',
            'name' => 'Bib Cock Praseo - G5804A1', 'price' => 2310, 'unit_id' => 'Pcs',
            'name' => 'Bib Cock - Terovit - SLK', 'price' => 1850, 'unit_id' => 'Pcs',
            'name' => 'Bib Cock - Terovit - IG', 'price' => 1870, 'unit_id' => 'Pcs',
            'name' => 'Bib Cock - Terovit - Fusion', 'price' => 2580, 'unit_id' => 'Pcs',
            'name' => 'Long Body Uno - T5006A1', 'price' => 2590, 'unit_id' => 'Pcs',
            'name' => 'Long Body Praseo - G5806A1', 'price' => 2770, 'unit_id' => 'Pcs',
            'name' => 'Long Body - Terovit - SLK', 'price' => 2230, 'unit_id' => 'Pcs',
            'name' => 'Long Body - Terovit - IG', 'price' => 2270, 'unit_id' => 'Pcs',
            'name' => 'Bib Cock 2 Way -Terovit - SLK', 'price' => 2980, 'unit_id' => 'Pcs',
            'name' => 'Bib Cock 2 Way -Terovit - IG', 'price' => 2890, 'unit_id' => 'Pcs',
            'name' => 'Pillar Cock - Terovit - SLK', 'price' => 1940, 'unit_id' => 'Pcs',
            'name' => 'Pillar Cock - Terovit - IG', 'price' => 2200, 'unit_id' => 'Pcs',
            'name' => 'Groute 1kg - SPL', 'price' => 180, 'unit_id' => 'Pkt/n',
            'name' => 'Groute 1kg - Epoxy', 'price' => 1450, 'unit_id' => 'Pkt/n',
            'name' => 'Head Shower - 6*6*18""', 'price' => 2950, 'unit_id' => 'Set/n',
            'name' => 'Head Shower - 6*6*22""', 'price' => 3400, 'unit_id' => 'Set/n',
            'name' => 'Head Shower - 8*8*22""', 'price' => 3600, 'unit_id' => 'Set/n',
            'name' => 'Head Shower - Normal', 'price' => 950, 'unit_id' => 'Set/n',
            'name' => 'Head Shower - 4*4*18""', 'price' => 1450, 'unit_id' => 'Set/n',
            'name' => 'Ppr Pipe 20mm SDR7.4 - 3mtr', 'price' => 393, 'unit_id' => 'Pcs',
            'name' => 'Ppr Pipe 25mm SDR7.4 - 3mtr', 'price' => 630, 'unit_id' => 'Pcs',
            'name' => 'Ppr Pipe 32mm SDR7.4 - 3mtr', 'price' => 1017, 'unit_id' => 'Pcs',
            'name' => 'Ppr Pipe 40mm SDR7.4 - 3mtr', 'price' => 1599, 'unit_id' => 'Pcs',
            'name' => 'Ppr Pipe 50mm SDR7.4 - 3mtr', 'price' => 2484, 'unit_id' => 'Pcs',
            'name' => 'Ppr Pipe 63mm SDR7.4 - 3mtr', 'price' => 3840, 'unit_id' => 'Pcs',
            'name' => 'Ppr Pipe 20mm SDR7.4', 'price' => 131, 'unit_id' => 'Mtr',
            'name' => 'Ppr Pipe 25mm SDR7.4 ', 'price' => 210, 'unit_id' => 'Mtr',
            'name' => 'Ppr Pipe 32mm SDR7.4 ', 'price' => 339, 'unit_id' => 'Mtr',
            'name' => 'Ppr Pipe 40mm SDR7.4 ', 'price' => 533, 'unit_id' => 'Mtr',
            'name' => 'Ppr Pipe 50mm SDR7.4 ', 'price' => 828, 'unit_id' => 'Mtr',
            'name' => 'Ppr Pipe 63mm SDR7.4 ', 'price' => 1280, 'unit_id' => 'Mtr',
            'name' => 'Ppr Elbow 20mm', 'price' => 23, 'unit_id' => 'Pcs',
            'name' => 'Ppr Elbow 25mm', 'price' => 43, 'unit_id' => 'Pcs',
            'name' => 'Ppr Elbow 32mm', 'price' => 70, 'unit_id' => 'Pcs',
            'name' => 'Ppr Elbow 40mm', 'price' => 148, 'unit_id' => 'Pcs',
            'name' => 'Ppr Elbow 50mm', 'price' => 249, 'unit_id' => 'Pcs',
            'name' => 'Ppr Elbow 63mm', 'price' => 439, 'unit_id' => 'Pcs',
            'name' => 'Ppr Elbow 45 20mm', 'price' => 29, 'unit_id' => 'Pcs',
            'name' => 'Ppr Elbow 45 25mm', 'price' => 48, 'unit_id' => 'Pcs',
            'name' => 'Ppr Elbow 45 32mm', 'price' => 73, 'unit_id' => 'Pcs',
            'name' => 'Ppr Elbow 45 40mm', 'price' => 141, 'unit_id' => 'Pcs',
            'name' => 'Ppr Elbow 45 50mm', 'price' => 238, 'unit_id' => 'Pcs',
            'name' => 'Ppr Elbow 45 63mm', 'price' => 370, 'unit_id' => 'Pcs',
            'name' => 'Ppr Socket 63mm', 'price' => 234, 'unit_id' => 'Pcs',
            'name' => 'Ppr Socket 20mm', 'price' => 17, 'unit_id' => 'Pcs',
            'name' => 'Ppr Socket 25mm', 'price' => 24, 'unit_id' => 'Pcs',
            'name' => 'Ppr Socket 32mm', 'price' => 43, 'unit_id' => 'Pcs',
            'name' => 'Ppr Socket 40mm', 'price' => 82, 'unit_id' => 'Pcs',
            'name' => 'Ppr Socket 50mm', 'price' => 138, 'unit_id' => 'Pcs',
            'name' => 'Ppr Tee 20mm', 'price' => 30, 'unit_id' => 'Pcs',
            'name' => 'Ppr Tee 25mm', 'price' => 50, 'unit_id' => 'Pcs',
            'name' => 'Ppr Tee 32mm', 'price' => 88, 'unit_id' => 'Pcs',
            'name' => 'Ppr Tee 40mm', 'price' => 173, 'unit_id' => 'Pcs',
            'name' => 'Ppr Tee 50mm', 'price' => 287, 'unit_id' => 'Pcs',
            'name' => 'Ppr Tee 63mm', 'price' => 522, 'unit_id' => 'Pcs',
            'name' => 'Ppr Union 20mm', 'price' => 98, 'unit_id' => 'Pcs',
            'name' => 'Ppr Union 25mm', 'price' => 167, 'unit_id' => 'Pcs',
            'name' => 'Ppr Union 32mm', 'price' => 263, 'unit_id' => 'Pcs',
            'name' => 'Ppr Union 40mm', 'price' => 451, 'unit_id' => 'Pcs',
            'name' => 'Ppr Union 50mm', 'price' => 707, 'unit_id' => 'Pcs',
            'name' => 'Ppr Union 63mm', 'price' => 844, 'unit_id' => 'Pcs',
            'name' => 'Ppr End Cap 20mm', 'price' => 31, 'unit_id' => 'Pcs',
            'name' => 'Ppr End Cap 25mm', 'price' => 46, 'unit_id' => 'Pcs',
            'name' => 'Ppr End Cap 32mm', 'price' => 70, 'unit_id' => 'Pcs',
            'name' => 'Ppr End Cap 40mm', 'price' => 111, 'unit_id' => 'Pcs',
            'name' => 'Ppr End Cap 50mm', 'price' => 187, 'unit_id' => 'Pcs',
            'name' => 'Ppr End Cap 63mm', 'price' => 338, 'unit_id' => 'Pcs',
            'name' => 'Ppr BallValve 20mm-Local', 'price' => 250, 'unit_id' => 'Pcs',
            'name' => 'Ppr BallValve 25mm-Local', 'price' => 350, 'unit_id' => 'Pcs',
            'name' => 'Ppr BallValve 32mm-Local ', 'price' => 450, 'unit_id' => 'Pcs',
            'name' => 'Ppr M.Union 20mm ', 'price' => 490, 'unit_id' => 'Pcs',
            'name' => 'Ppr M.Union 25mm ', 'price' => 705, 'unit_id' => 'Pcs',
            'name' => 'Ppr M.Union 32mm ', 'price' => 1033, 'unit_id' => 'Pcs',
            'name' => 'Ppr BallValve 20mm -NP', 'price' => 516, 'unit_id' => 'Pcs',
            'name' => 'Ppr BallValve 25mm -NP', 'price' => 720, 'unit_id' => 'Pcs',
            'name' => 'Ppr BallValve 32mm -NP', 'price' => 1210, 'unit_id' => 'Pcs',
            'name' => 'Ppr BallValve 40mm -NP', 'price' => 2005, 'unit_id' => 'Pcs',
            'name' => 'Ppr BallValve 50mm D/U-NP', 'price' => 3883, 'unit_id' => 'Pcs',
            'name' => 'Ppr BallValve 63mm D/U-NP', 'price' => 4970, 'unit_id' => 'Pcs',
            'name' => 'Ppr BallValve 20mm D/U-Local', 'price' => 580, 'unit_id' => 'Pcs',
            'name' => 'Ppr BallValve 25mm D/U-Local', 'price' => 750, 'unit_id' => 'Pcs',
            'name' => 'Ppr BallValve 32mm D/U-Local', 'price' => 1050, 'unit_id' => 'Pcs',
            'name' => 'Ppr BallValve 40mm D/U-NP', 'price' => 3104, 'unit_id' => 'Pcs',
            'name' => 'Ppr BallValve 32mm D/U-NP', 'price' => 2333, 'unit_id' => 'Pcs',
            'name' => 'Ppr BallValve 25mm D/U-NP', 'price' => 1608, 'unit_id' => 'Pcs',
            'name' => 'Ppr BallValve 20mm D/U-NP', 'price' => 1184, 'unit_id' => 'Pcs',
            'name' => 'Ppr F.Elbow 20mm', 'price' => 215, 'unit_id' => 'Pcs',
            'name' => 'Ppr F.Elbow 25mm', 'price' => 277, 'unit_id' => 'Pcs',
            'name' => 'Ppr F.Elbow 25*20mm', 'price' => 303, 'unit_id' => 'Pcs',
            'name' => 'Ppr F.Elbow 32mm', 'price' => 574, 'unit_id' => 'Pcs',
            'name' => 'Ppr F.Elbow 32*20mm', 'price' => 373, 'unit_id' => 'Pcs',
            'name' => 'Ppr F.S.Elbow 20mm', 'price' => 352, 'unit_id' => 'Pcs',
            'name' => 'Ppr F.S.Elbow 25*20mm', 'price' => 370, 'unit_id' => 'Pcs',
            'name' => 'Ppr F.S.Elbow 25mm', 'price' => 782, 'unit_id' => 'Pcs',
            'name' => 'Ppr M.Socket 20mm', 'price' => 251, 'unit_id' => 'Pcs',
            'name' => 'Ppr M.Socket 25mm', 'price' => 305, 'unit_id' => 'Pcs',
            'name' => 'Ppr M.Socket 32mm', 'price' => 677, 'unit_id' => 'Pcs',
            'name' => 'Ppr M.Socket 40mm', 'price' => 1120, 'unit_id' => 'Pcs',
            'name' => 'Ppr M.Socket 63mm', 'price' => 2406, 'unit_id' => 'Pcs',
            'name' => 'Ppr M.Socket 50mm', 'price' => 1807, 'unit_id' => 'Pcs',
            'name' => 'Ppr M.Socket 25*20mm', 'price' => 266, 'unit_id' => 'Pcs',
            'name' => 'Ppr M.Socket 32*20mm', 'price' => 339, 'unit_id' => 'Pcs',
            'name' => 'Ppr F.Socket 20mm', 'price' => 190, 'unit_id' => 'Pcs',
            'name' => 'Ppr F.Socket 25mm', 'price' => 237, 'unit_id' => 'Pcs',
            'name' => 'Ppr F.Socket 32mm', 'price' => 528, 'unit_id' => 'Pcs',
            'name' => 'Ppr F.Socket 40mm', 'price' => 983, 'unit_id' => 'Pcs',
            'name' => 'Ppr F.Socket 50mm', 'price' => 1365, 'unit_id' => 'Pcs',
            'name' => 'Ppr F.Socket 63mm', 'price' => 1846, 'unit_id' => 'Pcs',
            'name' => 'Ppr F.Socket 25*20mm', 'price' => 234, 'unit_id' => 'Pcs',
            'name' => 'Ppr F.Socket 32*20mm', 'price' => 227, 'unit_id' => 'Pcs',
            'name' => 'Sink Cock - Terovit-SLK', 'price' => 3250, 'unit_id' => 'Pcs',
            'name' => 'Sink 37*18 - Snow', 'price' => 3000, 'unit_id' => 'Pcs/n',
            'name' => 'Sink 37*18 - Imsge', 'price' => 4000, 'unit_id' => 'Pcs/n',
            'name' => 'Wash Basin Corner -Stallo', 'price' => 1250, 'unit_id' => 'Pcs/n',
            'name' => 'Single Set Commode - L', 'price' => 10500, 'unit_id' => 'Pcs/n',
            'name' => 'Wash Basin 16*20 - Stallo', 'price' => 1250, 'unit_id' => 'Pcs/n',
            'name' => 'Glass Self - ABS 18""', 'price' => 900, 'unit_id' => 'Pcs/n',
            'name' => 'Glass Self - ABS 22""', 'price' => 1100, 'unit_id' => 'Pcs/n',
            'name' => 'Glass Self - SS', 'price' => 480, 'unit_id' => 'Pcs/n',
            'name' => 'Fancy Mirror  50*35', 'price' => 550, 'unit_id' => 'Pcs/n',
            'name' => 'Bathroom Set - Buno', 'price' => 3200, 'unit_id' => 'Set/n',
            'name' => 'Fancy Mirror 60*45', 'price' => 1050, 'unit_id' => 'Pcs/n',
            'name' => 'Fancy Mirror - SPL- R', 'price' => 4000, 'unit_id' => 'Pcs/n',
            'name' => 'Check Valve 1"" -MD', 'price' => 450, 'unit_id' => 'Pcs/n',
            'name' => 'Fancy Mirror - SPL- Sq', 'price' => 3500, 'unit_id' => 'Pcs/n',
            'name' => 'Fancy Mirror - SPL- Digital - R', 'price' => 7000, 'unit_id' => 'Pcs/n',
            'name' => 'Fancy Mirror - Digital - ', 'price' => 4800, 'unit_id' => 'Pcs/n',
            'name' => 'Check Valve 3/4"" -MD', 'price' => 380, 'unit_id' => 'Pcs/n',
            'name' => 'C/S/Cock Terovit - SLK-15mm', 'price' => 2880, 'unit_id' => 'Pcs',
            'name' => 'Angle Valve - Poj.', 'price' => 550, 'unit_id' => 'Pcs/n',
            'name' => 'Mixer Leg For w/m,s/m', 'price' => 600, 'unit_id' => 'Set/n',
            'name' => 'Mixer Leg For B/m', 'price' => 250, 'unit_id' => 'Set/n',
            'name' => 'Upset - Hanging - Urinal', 'price' => 400, 'unit_id' => 'Set/n',
            'name' => 'Splender - Dix', 'price' => 180, 'unit_id' => 'Pcs/n',
            'name' => 'Splender - Czar', 'price' => 150, 'unit_id' => 'Pcs/n',
            'name' => 'Soap Dish - Lig', 'price' => 250, 'unit_id' => 'Pcs/n',
            'name' => 'Soap Dish - Havy', 'price' => 480, 'unit_id' => 'Pcs/n',
            'name' => 'Cpvc Brass Tee 3/4*1/2', 'price' => 212, 'unit_id' => 'Pcs',
            'name' => 'Pipe Huk - CH', 'price' => 6, 'unit_id' => 'Pcs/n',
            'name' => 'Water Tank 1000Ltr-Blow-Sarvottam', 'price' => 11000, 'unit_id' => 'Pcs/n',
            'name' => 'Water Tank 1000Ltr-**-Sarvottam', 'price' => 10000, 'unit_id' => 'Pcs/n',
            'name' => 'Water Tank 1000Ltr-***-Sarvottam', 'price' => 11000, 'unit_id' => 'Pcs/n',
            'name' => 'Water Tank 500Ltr-Blow-Sarvottam', 'price' => 5500, 'unit_id' => 'Pcs/n',
            'name' => 'Water Tank 500Ltr-**-Sarvottam', 'price' => 5000, 'unit_id' => 'Pcs/n',
            'name' => 'Water Tank 500Ltr-***-Sarvottam', 'price' => 5500, 'unit_id' => 'Pcs/n',
            'name' => 'Water Tank 2000Ltr-Blow-Sarvottam', 'price' => 22000, 'unit_id' => 'Pcs/n',
            'name' => 'Water Tank 5000Ltr-**Sarvottam', 'price' => 50000, 'unit_id' => 'Pcs/n',
            'name' => 'Water Tank 5000Ltr-***-Sarvottam', 'price' => 55000, 'unit_id' => 'Pcs/n',
            'name' => 'Water Tank 2000Ltr-Steel-SS-304', 'price' => 41000, 'unit_id' => 'Pcs/n',
            'name' => 'Water Tank 1000Ltr-Steel-SS-304', 'price' => 22000, 'unit_id' => 'Pcs/n',
            'name' => 'Water Tank 500Ltr-Steel-SS-304', 'price' => 14000, 'unit_id' => 'Pcs/n',
            'name' => 'Water Tank 2000Ltr-**-Sarvottam', 'price' => 20000, 'unit_id' => 'Pcs/n',
            'name' => 'Water Tank 2000Ltr-***-Sarvottam', 'price' => 22000, 'unit_id' => 'Pcs/n',
            'name' => 'Tiles Speciar - 2mm/3mm', 'price' => 150, 'unit_id' => 'Pkt/n',
            'name' => 'Golden 24 Crt - 50ml', 'price' => 200, 'unit_id' => 'Pcs/n',
            'name' => 'Golden 24 Crt - 100ml', 'price' => 400, 'unit_id' => 'Pcs/n',
            'name' => 'Golden 24 Crt - 200ml', 'price' => 800, 'unit_id' => 'Pcs/n',
            'name' => 'Golden 24 Crt - 500ml', 'price' => 2000, 'unit_id' => 'Pcs/n',
            'name' => 'Golden 24 Crt - 1000ml', 'price' => 4000, 'unit_id' => 'Pcs/n',
            'name' => 'Wash Basin Corner - C0408', 'price' => 3730, 'unit_id' => 'pcs',
            'name' => 'Wash Basin Kolar -455*330 - C042E', 'price' => 3180, 'unit_id' => 'Pcs',
            'name' => 'Wash Basin Indus -500*400 - C041B', 'price' => 2970, 'unit_id' => 'Pcs',
            'name' => 'Concrite Nail', 'price' => 2, 'unit_id' => 'Pcs/n',
            'name' => 'Bib Cock - Delta-CH', 'price' => 400, 'unit_id' => 'Pcs/n',
            'name' => 'Seal-O-Primer 20Ltr', 'price' => 10980, 'unit_id' => 'Pcs',
            'name' => 'Seal-O-Primer 10Ltr', 'price' => 6047, 'unit_id' => 'Pcs',
            'name' => 'Seal-O-Primer 4Ltr', 'price' => 2534, 'unit_id' => 'Pcs',
            'name' => 'Seal-O-Primer Ltr', 'price' => 725, 'unit_id' => 'Pcs',
            'name' => 'Cutting Blade - Tiles Special', 'price' => 300, 'unit_id' => 'Pcs/n',
            'name' => 'Cutting Blade - Wall / Marbel', 'price' => 250, 'unit_id' => 'Pcs/n',
            'name' => 'Ppr F.Tee 25*20mm', 'price' => 249, 'unit_id' => 'Pcs',
            'name' => 'Ppr F.Tee 32mm', 'price' => 650, 'unit_id' => 'Pcs',
            'name' => 'Ppr M.Tee 32mm', 'price' => 815, 'unit_id' => 'Pcs',
            'name' => 'Steel Jali 3""- H', 'price' => 80, 'unit_id' => 'Pcs/n',
            'name' => 'Steel Jali 4"" - H', 'price' => 160, 'unit_id' => 'Pcs/n',
            'name' => 'Brolac Enamel - 1Ltr-TrukBrown', 'price' => 974, 'unit_id' => 'Pcs',
            'name' => 'Brolac Enamel - 1Ltr-Black', 'price' => 974, 'unit_id' => 'Pcs',
            'name' => 'Brolac Enamel - 0.5Ltr-BusGreen', 'price' => 553, 'unit_id' => 'Pcs',
            'name' => 'Balvalve 1/2"" - Matrix', 'price' => 300, 'unit_id' => 'Pcs/n',
            'name' => 'Balvalve 3/4"" - Matrix', 'price' => 400, 'unit_id' => 'Pcs/n',
            'name' => 'Balvalve 1"" - Matrix', 'price' => 500, 'unit_id' => 'Pcs/n',
            'name' => 'Balvalve 1/2"" - Laxmi', 'price' => 927, 'unit_id' => 'Pcs',
            'name' => 'Balvalve 3/4"" - Laxmi', 'price' => 1241, 'unit_id' => 'Pcs',
            'name' => 'Balvalve 1"" - Laxmi', 'price' => 1854, 'unit_id' => 'Pcs',
            'name' => 'Sitcover S/P Commode-3160', 'price' => 1600, 'unit_id' => 'Pcs/n',
            'name' => 'Pvc Cistern D/F', 'price' => 2100, 'unit_id' => 'Pcs/n',
            'name' => 'Nojel - Brass -1*3/4""', 'price' => 120, 'unit_id' => 'Pcs/n',
            'name' => 'Nojel - Brass -1*1/2""', 'price' => 120, 'unit_id' => 'Pcs/n',
            'name' => 'Nojel - Brass - 1""', 'price' => 120, 'unit_id' => 'Pcs/n',
            'name' => 'Hos Clamp ', 'price' => 20, 'unit_id' => 'Pcs/n',
            'name' => 'Zebra Pipe - Normal', 'price' => 170, 'unit_id' => 'Kg/n',
            'name' => 'Sitcover S/P Commode-21987', 'price' => 1800, 'unit_id' => 'Pcs/n',
            'name' => 'Pillar Cock-Surgical', 'price' => 4500, 'unit_id' => 'Pcs',
            'name' => 'Cpvc Brass Tee 1/2""', 'price' => 167, 'unit_id' => 'Pcs',
            'name' => 'Sink 37*18 CH - MD', 'price' => 3400, 'unit_id' => 'Pcs',
            'name' => 'Tiles 24*24 - Nepovit -Regal Banco (4p)', 'price' => 98, 'unit_id' => 'Sqr/n',
            'name' => 'Adhishive SPL-For Tiles', 'price' => 740, 'unit_id' => 'Bag/n',
            'name' => 'God Tiles 12*18', 'price' => 350, 'unit_id' => 'Pcs/n',
            'name' => 'God Tiles 8*12', 'price' => 80, 'unit_id' => 'Pcs/n',
            'name' => 'God Tiles 8*12 - SPL', 'price' => 120, 'unit_id' => 'Pcs/n',
            'name' => 'Tiles 24*24 - Prime-Trepcana Aash (4p)', 'price' => 145, 'unit_id' => 'Sqr/n',
            'name' => 'Commod Spray Head Only', 'price' => 250, 'unit_id' => 'Pcs/n',
            'name' => 'Spray Tube 1mtr', 'price' => 300, 'unit_id' => 'Pcs/n',
            'name' => 'Spray Tube 1.5mtr', 'price' => 350, 'unit_id' => 'Pcs/n',
            'name' => 'Cistern Fitting (S/P)-Zeflow', 'price' => 2400, 'unit_id' => 'Set/n',
            'name' => 'Urinal - Stallo', 'price' => 1600, 'unit_id' => 'Pcs/n',
            'name' => 'Push Cock - Jenson', 'price' => 1800, 'unit_id' => 'Pcs/n',
            'name' => 'Dril Bit 6.5-Hamb.', 'price' => 90, 'unit_id' => 'Pcs/n',
            'name' => 'Grip & Screw', 'price' => 5, 'unit_id' => 'Set/n',
            'name' => 'Cistern Fitting (S/P)-CH', 'price' => 1200, 'unit_id' => 'Set/n',
            'name' => 'Splender - Parryware', 'price' => 480, 'unit_id' => 'Pcs/n',
            'name' => 'Push Pillar Cock - CH', 'price' => 950, 'unit_id' => 'Pcs/n',
            'name' => 'Upset - Mixtuet', 'price' => 150, 'unit_id' => 'Pcs/n',
            'name' => 'Tiles 24*48 Humira White (2p)', 'price' => 182, 'unit_id' => 'Sqr/n',
            'name' => 'Water Pump-1HP (SS-72) - Supertake', 'price' => 20100, 'unit_id' => 'Pcs',
            'name' => 'Manhole Cover 15*15 - 5 Ton', 'price' => 1840, 'unit_id' => 'Pcs',
            'name' => 'Manhole Cover 18*18 - 5 Ton', 'price' => 2810, 'unit_id' => 'Pcs',
            'name' => 'Manhole Cover 12*12 - 5 Ton', 'price' => 1450, 'unit_id' => 'Pcs',
            'name' => 'Manhole Cover 24*24 - 5 Ton', 'price' => 4910, 'unit_id' => 'Pcs',
            'name' => 'Manhole Cover 28*28 - 5 Ton', 'price' => 8620, 'unit_id' => 'Pcs',
            'name' => 'Manhole Cover 30*30 - 5 Ton', 'price' => 9240, 'unit_id' => 'Pcs',
            'name' => 'Manhole Cover 18*18 - 3 Ton', 'price' => 2750, 'unit_id' => 'Pcs',
            'name' => 'Manhole Cover 24*24 - 3 Ton', 'price' => 4500, 'unit_id' => 'Pcs',
            'name' => 'Ppr F.Tee 32*20mm', 'price' => 336, 'unit_id' => 'Pcs',
            'name' => 'Ppr R.Tee 32*20mm', 'price' => 83, 'unit_id' => 'Pcs',
            'name' => 'Long Body Tap-PVC', 'price' => 250, 'unit_id' => 'Pcs/n',
            'name' => 'Bib Cock Tap -PVC', 'price' => 180, 'unit_id' => 'Pcs/n',
            'name' => 'Bib Cock-PVC', 'price' => 100, 'unit_id' => 'Pcs/n',
            'name' => 'Bleaching Pouder', 'price' => 50, 'unit_id' => 'Pcs/n',
            'name' => 'Basin Mixture ""Chandset""', 'price' => 250, 'unit_id' => 'Pcs/n',
            'name' => 'Hand Shower ""Head""', 'price' => 480, 'unit_id' => 'Pcs/n',
            'name' => 'Spray holder', 'price' => 60, 'unit_id' => 'Pcs/n',
            'name' => 'Washer', 'price' => 5, 'unit_id' => 'Pcs/n',
            'name' => 'Tiles 12*18 Nitco - Grigio Venjo-DK (6p)', 'price' => 175, 'unit_id' => 'Sqr',
            'name' => 'Tiles 12*18 Nitco - Grigio Venjo-HL (6p)', 'price' => 175, 'unit_id' => 'Sqr',
            'name' => 'Tiles 12*18 Nitco - Grigio Venjo-Lig (6p)', 'price' => 175, 'unit_id' => 'Sqr',
            'name' => 'Tiles 24*24 Nepovit-Carara (4p)', 'price' => 96, 'unit_id' => 'Sqr/n',
            'name' => 'Tiles 12*12 Prime - Remote Lig. (8p)', 'price' => 125, 'unit_id' => 'Sqr/n',
            'name' => 'Tiles 24*48 Nitco - Sivic White (2p)', 'price' => 290, 'unit_id' => 'Sqr',
            'name' => 'Grenite - SPL', 'price' => 280, 'unit_id' => 'Sqr/n',
            'name' => 'Scapper 8""', 'price' => 210, 'unit_id' => 'Pcs/n',
            'name' => 'Ceramic Syphon', 'price' => 250, 'unit_id' => 'Pcs/n',
            'name' => 'Nojel - Brass - 3/4*1/2""', 'price' => 75, 'unit_id' => 'Pcs/n',
            'name' => 'Sink Coupling - M', 'price' => 220, 'unit_id' => 'Pcs/n',
            'name' => 'Khaxi Masin - 8""', 'price' => 35, 'unit_id' => 'Pcs/n',
            'name' => 'Brolac Enamel - 4Ltr -Black', 'price' => 3752, 'unit_id' => 'Pcs',
            'name' => 'Hax Nipple', 'price' => 60, 'unit_id' => 'Pcs/n',
            'name' => 'Pillar Cock-Uno -T5001A1', 'price' => 2430, 'unit_id' => 'Pcs',
            'name' => 'Poutch Screw 10mm', 'price' => 100, 'unit_id' => 'Set/n',
            'name' => 'Water Pump-1HP (Sup.100)-Sporty', 'price' => 20500, 'unit_id' => 'Pcs',
            'name' => 'Transportation Charge', 'price' => 0, 'unit_id' => 'Side To',
            'name' => 'Pvc Solvent - 500ml - R', 'price' => 595, 'unit_id' => 'Pcs',
            'name' => 'Tiles 12*18 Prime-Tervitino Lig (6p)', 'price' => 75, 'unit_id' => 'Sqr/n',
            'name' => 'Tiles 12*12 Prime - White (10p)', 'price' => 75, 'unit_id' => 'Sqr/n',
            'name' => 'Brolac Enamel - 1Ltr-GoldenBrown', 'price' => 974, 'unit_id' => 'Pcs',
            'name' => 'HDP Pipe - Local (6""/4"")', 'price' => 130, 'unit_id' => 'Kg/n',
            'name' => 'HDP Soket - 160mm-Local', 'price' => 230, 'unit_id' => 'Pcs',
            'name' => 'HDP Soket - 160mm-NS-Q', 'price' => 280, 'unit_id' => 'Pcs/n',
            'name' => 'HDP Bend - 160mm-local', 'price' => 395, 'unit_id' => 'Pcs',
            'name' => 'HDP R.Tee 160*110 -Local', 'price' => 520, 'unit_id' => 'Pcs',
            'name' => 'HDP R.Soket 160*110 -Local', 'price' => 270, 'unit_id' => 'Pcs',
            'name' => 'HDP R.Bend 160*110 -Local', 'price' => 450, 'unit_id' => 'Pcs',
            'name' => 'HDP Pipe (20/16)mm-Role - Local', 'price' => 155, 'unit_id' => 'Kg/n',
            'name' => 'Concrite Nail - 1kg-Pakt.', 'price' => 350, 'unit_id' => 'Pkt/n',
            'name' => 'Washer -  Commmode', 'price' => 350, 'unit_id' => 'Pcs/n',
            'name' => 'Tiles 16*16 Nepovit- LibraRoyal (6p)', 'price' => 82, 'unit_id' => 'Sqr/n',
            'name' => 'Tiles 12*18 Prime-Mirrag Dk.(6p)', 'price' => 75, 'unit_id' => 'Sqr/n',
            'name' => 'Pvc Vent Cowel - 110mm', 'price' => 103, 'unit_id' => 'Pcs',
            'name' => 'Pvc Vent Cowel - 75mm', 'price' => 54, 'unit_id' => 'Pcs',
            'name' => 'Pvc Vent Cowel - 160mm', 'price' => 158, 'unit_id' => 'Pcs',
            'name' => 'Glops', 'price' => 100, 'unit_id' => 'Pcs',
            'name' => 'Brolac Enamel - 4Ltr-TrukBrown', 'price' => 3752, 'unit_id' => 'Pcs',
            'name' => 'Pvc Jali 110mm', 'price' => 80, 'unit_id' => 'Pcs/n',
            'name' => 'Pvc End Cap 75mm', 'price' => 109, 'unit_id' => 'Pcs',
            'name' => 'Gi Long Nipple 1/2*2""', 'price' => 25, 'unit_id' => 'Pcs',
            'name' => 'Ppr R.Soket 25*20', 'price' => 29, 'unit_id' => 'Pcs',
            'name' => 'Ppr R.Soket 32*20', 'price' => 37, 'unit_id' => 'Pcs',
            'name' => 'Chapra', 'price' => 1600, 'unit_id' => 'Kg/n',
            'name' => 'Sprit', 'price' => 90, 'unit_id' => 'Bot./n',
            'name' => 'Sprit - 4Ltr', 'price' => 425, 'unit_id' => 'Jar/n',
            'name' => 'Single Set Commode Bia -12""-C8605', 'price' => 23080, 'unit_id' => 'Set',
            'name' => 'Single Set Commode Aquiline -12""-C8901', 'price' => 42030, 'unit_id' => 'Set',
            'name' => 'Single Set Commode Inslim -12""-C8905', 'price' => 37830, 'unit_id' => 'Set',
            'name' => 'Single Set Commode Omega -12""-C8906', 'price' => 42030, 'unit_id' => 'Set',
            'name' => 'Single Set Commode Blaze -12""-C8904', 'price' => 34850, 'unit_id' => 'Set',
            'name' => 'Single Set Commode Vanue -12""-C890N', 'price' => 31370, 'unit_id' => 'Set',
            'name' => 'Single Set Commode Gamma -8""-C025A', 'price' => 22550, 'unit_id' => 'Set',
            'name' => 'Single Set Commode Crown -P/T-C897G', 'price' => 21520, 'unit_id' => 'Set',
            'name' => 'Single Set Commode Stanza -12""-C897946', 'price' => 34870, 'unit_id' => 'Set',
            'name' => 'Nojel - Brass - 3/4""', 'price' => 75, 'unit_id' => 'Pcs/n',
            'name' => 'Single Set Commode Hind.-12""-Studio', 'price' => 17884, 'unit_id' => 'Pcs/n',
            'name' => 'White Cement - 5kg', 'price' => 250, 'unit_id' => 'Pkt/n',
            'name' => 'Hand Dryer', 'price' => 4650, 'unit_id' => 'Pcs/n',
            'name' => 'Gate Valve - DTC - 1""', 'price' => 1840, 'unit_id' => 'Pcs/n',
            'name' => 'Wash Basin 13*18 - Stallo -L', 'price' => 1200, 'unit_id' => 'Pcs/n',
            'name' => 'Pillar Cock - CH', 'price' => 450, 'unit_id' => 'Pcs/n',
            'name' => 'Gi Long Nipple 1/2*9""', 'price' => 110, 'unit_id' => 'Pcs/n',
            'name' => 'Cutting Blade - Metal', 'price' => 20, 'unit_id' => 'Pcs/n',
            'name' => 'Tiles 12*18 Prime-Pristine -Dk (6p)', 'price' => 75, 'unit_id' => 'Set/n',
            'name' => 'Tiles 12*18 Prime-Pristine -Lig (6p)', 'price' => 75, 'unit_id' => 'Sqr/n',
            'name' => 'Tiles 12*12 Prime-Pristine -Fl (10p)', 'price' => 75, 'unit_id' => 'Sqr/n',
            'name' => 'Groute 1/2kg - Local', 'price' => 50, 'unit_id' => 'Pkt/n',
            'name' => 'Tiles 8*12 - Wh/Iv (12p)', 'price' => 60, 'unit_id' => 'Sqr/n',
            'name' => 'Ramtilak', 'price' => 25, 'unit_id' => 'Pkt/n',
            'name' => 'Sitcover S/P Commode-21025 (Sq.)', 'price' => 2150, 'unit_id' => 'Pcs/n',
            'name' => '23512IN-Cp Spouts - Kohler', 'price' => 0, 'unit_id' => 'Pcs',
            'name' => '73038T-Cl-Cp - O/H Shower', 'price' => 0, 'unit_id' => 'Pcs',
            'name' => 'Dampstop - 2kg', 'price' => 1808, 'unit_id' => 'Pcs',
            'name' => 'Dampstop - 5kg', 'price' => 4427, 'unit_id' => 'Pcs',
            'name' => 'Dampstop - 10kg', 'price' => 8526, 'unit_id' => 'Pcs',
            'name' => 'Tiles 24*48 NeMato-Trident Bainco (2p)', 'price' => 160, 'unit_id' => 'Sqr/n',
            'name' => 'Tiles 12*12 Prime - Remote DK. (8p)', 'price' => 125, 'unit_id' => 'Sqr/n',
            'name' => 'Tiles 12*12 Prime-Tervitino -Fl (10p)', 'price' => 75, 'unit_id' => 'Sqr/n',
            'name' => 'Tiles 24*24 Nepovit -Carara (4p)', 'price' => 96, 'unit_id' => 'Sqr/n',
            'name' => 'Tiles 24*48 Nitco - Avollan Slate (2p)', 'price' => 208, 'unit_id' => 'Sqr/n',
            'name' => 'Fancy Mirror  50*35 - Eching', 'price' => 750, 'unit_id' => 'Pcs/n',
            'name' => 'Brolac Enamel - 0.5Ltr-SmokeGrey', 'price' => 513, 'unit_id' => 'Pcs',
            'name' => 'Gi Tee 1/2""', 'price' => 147, 'unit_id' => 'Pcs',
            'name' => 'Gi Elbow 1/2""', 'price' => 98, 'unit_id' => 'Pcs',
            'name' => 'Swan Neck (P/C) - SLK.', 'price' => 3250, 'unit_id' => 'Pcs',
            'name' => 'Swan Neck (P/C) - IG.', 'price' => 3010, 'unit_id' => 'Pcs',
            'name' => 'Gi Socket 1/2""', 'price' => 87, 'unit_id' => 'Pcs',
            'name' => 'Brush Holder - Buno', 'price' => 480, 'unit_id' => 'Pcs/n',
            'name' => 'Cloths', 'price' => 75, 'unit_id' => 'Pcs/n',
            'name' => 'Gi Long Nipple 1/2*4""', 'price' => 80, 'unit_id' => 'Pcs',
            'name' => 'Pvc Pipe 75mm-6kg-NS-3mtr', 'price' => 1566, 'unit_id' => 'Pcs',
            'name' => 'Cpvc Brass Tee 1*1/2""', 'price' => 372, 'unit_id' => 'Pcs',
            'name' => 'HDP Bend - 160mm-45*-local', 'price' => 380, 'unit_id' => 'Pcs',
            'name' => 'Brolac Enamel - 0.5Ltr-Black', 'price' => 513, 'unit_id' => 'Pcs',
            'name' => 'Brolac Enamel - 1Ltr-SmokeGrey', 'price' => 974, 'unit_id' => 'Pcs',
            'name' => 'Water Pump-1HP (SS-71) - Supertake', 'price' => 14840, 'unit_id' => 'Pcs',
            'name' => 'Tar Bruss', 'price' => 45, 'unit_id' => 'Pcs/n',
            'name' => 'Steel Jhush', 'price' => 250, 'unit_id' => 'Pkt/n',
            'name' => 'Dori (Jut)', 'price' => 10, 'unit_id' => 'Pcs/n',
            'name' => 'Silk Glamour - 1ltr', 'price' => 1980, 'unit_id' => 'Pcs',
            'name' => 'Paper Holder -Ss', 'price' => 350, 'unit_id' => 'Pcs/n',
            'name' => 'Paper Holder - Viking', 'price' => 2250, 'unit_id' => 'Pcs/n',
            'name' => 'Paper Holder - Ribko', 'price' => 1250, 'unit_id' => 'Pcs/n',
            'name' => 'Mixer Crunch - H', 'price' => 650, 'unit_id' => 'Pcs/n',
            'name' => 'Tiles 16*16 Nepovit-AtlasTreviso (6p)', 'price' => 88, 'unit_id' => 'Sqr/n',
            'name' => 'Tiles 24*24 Nitco - Oregon Black (4p)', 'price' => 225, 'unit_id' => 'Sqr',
            'name' => 'Tiles 12*24 Prime - Distiny-Lt', 'price' => 98, 'unit_id' => 'Sqr/n',
            'name' => 'Sink 37*18 D/B - H/M Black/Silver', 'price' => 10400, 'unit_id' => 'Set/n',
            'name' => 'Tiles 12*12 Prime-Distiny-Fl (10p)', 'price' => 75, 'unit_id' => 'Sqr/n',
            'name' => 'Damp Shield Elasto - 20Ltr', 'price' => 21487, 'unit_id' => 'Pcs',
            'name' => 'Damp Shield Elasto - 10Ltr', 'price' => 10868, 'unit_id' => 'Pcs',
            'name' => 'Damp Shield Elasto - 4Ltr', 'price' => 4409, 'unit_id' => 'Pcs',
            'name' => 'Damp Shield Elasto - 1Ltr', 'price' => 1124, 'unit_id' => 'Pcs',
            'name' => 'Single Set Commode -Pry.-12""-Nuva', 'price' => 31736, 'unit_id' => 'Pcs',
            'name' => 'Tiles 12*18 Prime -PlainWhite -(6p)', 'price' => 75, 'unit_id' => 'Sqr/n',
            'name' => 'Bondtite Supper Strength -180gm', 'price' => 430, 'unit_id' => 'Set/n',
            'name' => 'Bondtite Supper Strength -450gm', 'price' => 1045, 'unit_id' => 'Set/n',
            'name' => 'Bondtite Supper Strength -900gm', 'price' => 1536, 'unit_id' => 'Set/n',
            'name' => 'Bondtite Supper Strength -1.8kg', 'price' => 2715, 'unit_id' => 'Set/n',
            'name' => 'Urinal Niagara N - C0579', 'price' => 4210, 'unit_id' => 'Pcs',
            'name' => 'Urinal Patitation - C0571', 'price' => 6030, 'unit_id' => 'Pcs',
            'name' => 'Gi Long Nipple 1/2*6""', 'price' => 90, 'unit_id' => 'Pcs',
            'name' => 'Threed Rod 10mm', 'price' => 450, 'unit_id' => 'Pcs/n',
            'name' => 'Bullate Grip', 'price' => 35, 'unit_id' => 'Pcs/n',
            'name' => 'Upset - Leg (S/W) Mixtuet', 'price' => 600, 'unit_id' => 'Set/n',
            'name' => 'Mixer Nut', 'price' => 180, 'unit_id' => 'Set/n',
            'name' => 'Khaxi Masin - 4"" - Wood', 'price' => 35, 'unit_id' => 'Pcs/n',
            'name' => 'Dhago', 'price' => 15, 'unit_id' => 'Pcs/n',
            'name' => 'Garu', 'price' => 25, 'unit_id' => 'Pcs/n',
            'name' => 'Ppr R.Tee 32*25mm', 'price' => 87, 'unit_id' => 'Pcs',
            'name' => 'Ppr R.Soket 32*25mm', 'price' => 42, 'unit_id' => 'Pcs',
            'name' => 'Ppr F.Union 32mm', 'price' => 993, 'unit_id' => 'Pcs',
            'name' => 'Ppr C-Over 25mm', 'price' => 203, 'unit_id' => 'Pcs',
            'name' => 'Ppr D.F.Elbow (Mixur) 25*20mm', 'price' => 588, 'unit_id' => 'Pcs',
            'name' => 'Steel Clamp 1""', 'price' => 15, 'unit_id' => 'Pcs/n',
            'name' => 'Steel clamp 3/4""', 'price' => 12, 'unit_id' => 'Pcs/n',
            'name' => 'Steel clamp 1/2""', 'price' => 10, 'unit_id' => 'Pcs/n',
            'name' => 'Diverter Body (U/H/F)-G4888A1', 'price' => 7030, 'unit_id' => 'Pcs',
            'name' => 'Diverter Body (3-Inlet)-G9969A1', 'price' => 8790, 'unit_id' => 'Pcs',
            'name' => 'Diverter Body BasinMixue-G9002A1', 'price' => 5310, 'unit_id' => 'Pcs',
            'name' => 'Ppr C-Tee 25mm', 'price' => 75, 'unit_id' => 'Pcs',
            'name' => 'Sink 24*18*8 H/M', 'price' => 5600, 'unit_id' => 'Pcs/n',
            'name' => 'Sink 16*18*8 H/M', 'price' => 4400, 'unit_id' => 'Pcs/n',
            'name' => 'Tiles 32*64 Nitco - OrobicoGrish(2p)', 'price' => 345, 'unit_id' => 'Sqr',
            'name' => 'Sink Mixer Uno-T5035A1', 'price' => 7440, 'unit_id' => 'Set',
            'name' => 'Diverter Upprt Trim-UHF Praseo-G5886A1', 'price' => 2980, 'unit_id' => 'Set',
            'name' => 'Diverter Upprt Trim-UHF Quattro-T2385A1', 'price' => 4080, 'unit_id' => 'Set',
            'name' => 'Wall Mixer S/L-OHS Aqua - G5754A1', 'price' => 12870, 'unit_id' => 'Set',
            'name' => 'Head Shower - 250*170*15 - T9839A1', 'price' => 7170, 'unit_id' => 'Pcs',
            'name' => 'Head Shower - 200mm - T9844A1', 'price' => 3460, 'unit_id' => 'Pcs',
            'name' => 'Head Shower - 230mm - T9840A1', 'price' => 4650, 'unit_id' => 'Pcs',
            'name' => 'Shower Arm 24"" - T9949A1', 'price' => 4870, 'unit_id' => 'Pcs',
            'name' => 'Shower Arm 18"" - T5040A1', 'price' => 3510, 'unit_id' => 'Pcs',
            'name' => 'Pedestal Long Standard - C0371', 'price' => 4900, 'unit_id' => 'Pcs',
            'name' => 'Single Set Commode -Jaquer.-12""-', 'price' => 23989, 'unit_id' => 'Pcs/n',
            'name' => 'Bib Cock 2 Way Praseo - G5834A1', 'price' => 3690, 'unit_id' => 'Pcs',
            'name' => 'Bib Cock 2 Way Claret - G5234A1', 'price' => 3340, 'unit_id' => 'Pcs',
            'name' => 'Concealed Cistern Linea-F/F-E812299', 'price' => 28030, 'unit_id' => 'Set',
            'name' => 'Concealed Cistern Linea-H/F-E812599', 'price' => 17040, 'unit_id' => 'Set',
            'name' => 'Push Plate Linea - E8223A1', 'price' => 3660, 'unit_id' => 'Pcs',
            'name' => 'Push Plate Linea - E8220A1', 'price' => 3660, 'unit_id' => 'Pcs',
            'name' => 'Push Plate Linea - E8219A1', 'price' => 3660, 'unit_id' => 'Pcs',
            'name' => 'Diverter Upprt Trim-UHF-Adge-G4885A1', 'price' => 3040, 'unit_id' => 'Set',
            'name' => 'Spouts Long - G572XA1', 'price' => 3620, 'unit_id' => 'Pcs',
            'name' => 'Spouts Long - G572YA1', 'price' => 3410, 'unit_id' => 'Pcs',
            'name' => 'Spouts Clerat - T4628A1', 'price' => 2600, 'unit_id' => 'Pcs',
            'name' => 'Bib Cock Terovit - IG - Nozel', 'price' => 2270, 'unit_id' => 'Pcs',
            'name' => 'Wall Hung W/C Grand Hi-Jet-C8934', 'price' => 38030, 'unit_id' => 'Set',
            'name' => 'Wall Hung W/C Cute - C8846', 'price' => 14770, 'unit_id' => 'Set',
            'name' => 'Wall Hung W/C Splendor - C8671', 'price' => 28700, 'unit_id' => 'Set',
            'name' => 'Wall Hung W/C Superio Rimless-C890X', 'price' => 27670, 'unit_id' => 'Set',
            'name' => 'Wall Hung W/C Oasis -C8670', 'price' => 27670, 'unit_id' => 'Set',
            'name' => 'Spouts Praseo - T1327A1', 'price' => 2730, 'unit_id' => 'Pcs',
            'name' => 'Spouts With Pin Praseo - T1328A1', 'price' => 3710, 'unit_id' => 'Pcs',
            'name' => 'Bathroom Set Viking  (5p)-Art1680', 'price' => 18650, 'unit_id' => 'Set',
            'name' => 'Bathroom Set Viking  (5p)-Art2251', 'price' => 9050, 'unit_id' => 'set',
            'name' => 'Bathroom Set Viking  (5p)-Art1940', 'price' => 12325, 'unit_id' => 'Set',
            'name' => 'Bathroom Set Viking  (5p)-Art1920', 'price' => 12750, 'unit_id' => 'Set',
            'name' => 'Paper Holder Viking - Art1691', 'price' => 3165, 'unit_id' => 'Pcs',
            'name' => 'Paper Holder Viking - Art1932', 'price' => 3450, 'unit_id' => 'Pcs',
            'name' => 'K-28780IN0 -W/H Commode', 'price' => 35795, 'unit_id' => 'Pcs',
            'name' => 'K-287881IN0 - Seat Cover', 'price' => 15669, 'unit_id' => 'Pcs',
            'name' => 'K-1046327 - Connector-W/H/C', 'price' => 1231, 'unit_id' => 'Pcs',
            'name' => 'K-4177IN-M-CP Push Plate', 'price' => 4556, 'unit_id' => 'Pcs',
            'name' => 'K-75823IN-CP - Bottle Trap', 'price' => 6397, 'unit_id' => 'Set',
            'name' => 'K-27500IN-4FP-CP -Diverter Upper Plate', 'price' => 4091, 'unit_id' => 'Pcs',
            'name' => 'K-99450IN-B4ND-CP -Spouts B/M', 'price' => 6607, 'unit_id' => 'Pcs',
            'name' => 'K-23973IN-CP-Spouts - Vive', 'price' => 8308, 'unit_id' => 'Pcs',
            'name' => 'K-45432IN-CP - PopUp Coupling', 'price' => 1349, 'unit_id' => 'Pcs',
            'name' => 'Sink Cock Uno - T5021A1', 'price' => 3750, 'unit_id' => 'Pcs',
            'name' => 'Sink Mixer S/L (W/M) - Aqua - G571XA1', 'price' => 8560, 'unit_id' => 'Set',
            'name' => 'Parish - 20kg', 'price' => 750, 'unit_id' => 'Bag/n',
            'name' => 'Tiles 12*18 Nitco - TuscanGrey-DK (6p)', 'price' => 175, 'unit_id' => 'Sqr',
            'name' => 'Tiles 12*18 Nitco - TuscanGrey-Lg (6p)', 'price' => 175, 'unit_id' => 'Sqr',
            'name' => 'Tiles 24*24 ATS - 720', 'price' => 115, 'unit_id' => 'Sqr/n',
            'name' => 'Tiles 12*12 Nitco - Oscae Blue', 'price' => 200, 'unit_id' => 'Sqr',
            'name' => 'K-25150In-Na (B/M Divertor)', 'price' => 0, 'unit_id' => 'cs',
            'name' => 'K-72290IN-4-BV (Divertor Upper Plate-Aleo', 'price' => 0, 'unit_id' => 'cs',
            'name' => 'Brolac Enamel - 4Ltr-GoldenBrown', 'price' => 3752, 'unit_id' => 'Pcs',
            'name' => 'Spray holder - Havy', 'price' => 200, 'unit_id' => 'Pcs',
            'name' => 'Pvc End Cap 110mm', 'price' => 170, 'unit_id' => 'Pcs',
            'name' => 'Gi Long Nipple 3/4*12""', 'price' => 300, 'unit_id' => 'Pcs',
            'name' => 'Nojel Cock - Loking', 'price' => 330, 'unit_id' => 'Pcs/n',
            'name' => 'Silicone W/B Yeti - 4lit', 'price' => 3553, 'unit_id' => 'Pcs',
            'name' => 'Tiles 12*12 Prime - Alfa 07 - (8p)', 'price' => 125, 'unit_id' => 'Sqr/n',
            'name' => 'Angle Valve Trigon - T9828A1', 'price' => 1070, 'unit_id' => 'Pcs',
            'name' => 'Swan Neck P/C - Uno - T5003A1', 'price' => 3640, 'unit_id' => 'Pcs',
            'name' => 'Cpvc Cross over - 3/4""', 'price' => 223, 'unit_id' => 'Pcs',
            'name' => 'Brolac Enamel - 1Ltr-BusGreen', 'price' => 974, 'unit_id' => 'Pcs',
            'name' => 'Sink 32*18 - Image', 'price' => 3800, 'unit_id' => 'Pcs/n',
            'name' => 'Water Pump Submercial/Laltin-1HP - CH', 'price' => 7600, 'unit_id' => 'Pcs',
            'name' => 'Tiles 12*18 Prime-Florida -Dk (6p)', 'price' => 75, 'unit_id' => 'Set/n',
            'name' => 'Tiles 12*18 Prime-Florida -Lig (6p)', 'price' => 75, 'unit_id' => 'Sqr/n',
            'name' => 'Tiles 12*18 Prime-Florida -Hl (6p)', 'price' => 75, 'unit_id' => 'Sqr/n',
            'name' => 'Tiles 12*12 Prime-Alcazar -Fl (10p)', 'price' => 75, 'unit_id' => 'Sqr/n',
            'name' => 'Tiles 16*16 Nepovit-RubyMulti (6p)', 'price' => 88, 'unit_id' => 'Sqr/n',
            'name' => 'Tiles 12*24 Prime - Dove -Lt', 'price' => 98, 'unit_id' => 'Sqr/n',
            'name' => 'Tiles 12*24 Prime - Dove -Hl', 'price' => 98, 'unit_id' => 'Sqr/n',
            'name' => 'Sitcover S/P Commode-LPA023/Reg.', 'price' => 1450, 'unit_id' => 'Pcs/n',
            'name' => 'Cabinet W/B 18*32', 'price' => 38500, 'unit_id' => 'Set/n',
            'name' => 'Ballcock-CH - 1/2""', 'price' => 550, 'unit_id' => 'Pcs/n',
            'name' => 'Towel Ring - Buno', 'price' => 480, 'unit_id' => 'Pcs/n',
            'name' => 'CP Tee', 'price' => 280, 'unit_id' => 'Pcs/n',
            'name' => 'Connection Pipe 36"" SPL', 'price' => 330, 'unit_id' => 'Pcs/n',
            'name' => 'Ppr Plug 20mm - Threed', 'price' => 20, 'unit_id' => 'Pcs/n',
            'name' => 'Red Oxide - 1Kg', 'price' => 125, 'unit_id' => 'Pkt/n',
            'name' => 'Brolac Enamel - 1Ltr-Pheroja', 'price' => 974, 'unit_id' => 'Pcs',
            'name' => 'Tiles 12*18 Prime -Mosaic-Dk (6p)', 'price' => 75, 'unit_id' => 'Sqr/n',
            'name' => 'Tiles 12*18 Prime -Mosaic-Lig (6p)', 'price' => 75, 'unit_id' => 'Sqr/n',
            'name' => 'Tiles 12*12 Prime - Vista (8p)', 'price' => 122, 'unit_id' => 'Sqr/n',
            'name' => 'Tiles 24*24 Prime-Antique Aash (4p)', 'price' => 155, 'unit_id' => 'Sqr/n',
            'name' => 'Tiles 12*12 Prime - Mosaic (10p)', 'price' => 75, 'unit_id' => 'Sqr/n',
            'name' => 'Tiles 12*24 Prime - Ford -Hl', 'price' => 98, 'unit_id' => 'Sqr/n',
            'name' => 'Tiles 12*24 Prime - Ford -Lig.', 'price' => 98, 'unit_id' => 'Sqr/n',
            'name' => 'Silk Illusion Non Metallic 1Ltr', 'price' => 1611, 'unit_id' => 'Pcs',
            'name' => 'Silicone W/B Yeti - 10lit', 'price' => 0, 'unit_id' => 'Pcs',
            'name' => 'Silicone W/B Yeti - 1lit', 'price' => 0, 'unit_id' => 'Pcs',
            'name' => 'Brolac Enamel - 4Ltr-SmokeGrey', 'price' => 3752, 'unit_id' => 'Pcs',
            'name' => 'Brolac Enamel - 0.5Ltr-GoldenBrown', 'price' => 513, 'unit_id' => 'Pcs',
            'name' => 'Urinal NewMagnum - C3583', 'price' => 12890, 'unit_id' => 'Pcs',
            'name' => 'Wash Basin VintoSmart (560*482) -C898A', 'price' => 3260, 'unit_id' => 'Pcs',
            'name' => 'Pedestal Long VintoSmart -C898B', 'price' => 3020, 'unit_id' => 'Pcs',
            'name' => 'Wash Basin Casa - (570*440) -C0404', 'price' => 3770, 'unit_id' => 'Pcs',
            'name' => 'Pedestal Long Casa - C0380', 'price' => 3120, 'unit_id' => 'Pcs',
            'name' => 'Wash Basin LucoSmart - (560*450) -C8981', 'price' => 3450, 'unit_id' => 'Pcs',
            'name' => 'Pedestal Long LuchoSmart -C0385', 'price' => 3180, 'unit_id' => 'Pcs',
            'name' => 'Soap Dish- Double - Havy', 'price' => 950, 'unit_id' => 'Pcs/n',
            'name' => 'Urinal Spreader NiagraN - E8113', 'price' => 930, 'unit_id' => 'Pcs',
            'name' => 'Urinal Spreader NewMagnum - E8095', 'price' => 1280, 'unit_id' => 'Pcs',
            'name' => 'Furel Cock - H', 'price' => 880, 'unit_id' => 'Pcs/n',
            'name' => 'Gi Union 1/2""', 'price' => 310, 'unit_id' => 'Pcs',
            'name' => 'Tiles 16*16 - 1001', 'price' => 78, 'unit_id' => 'Sqr/n',
            'name' => 'Bal Cock (S/P Commode)', 'price' => 1050, 'unit_id' => 'Pcs/n',
            'name' => 'Bal cock (S/P Commode) - CH', 'price' => 550, 'unit_id' => 'Pcs/n',
            'name' => 'Brolac Enamel - 0.5Ltr-TrukBrown', 'price' => 513, 'unit_id' => 'Pcs',
            'name' => 'HDP Pipe - Local - 8""', 'price' => 155, 'unit_id' => 'Kg/n',
            'name' => 'HDP Soket - 200(8"")mm-Local', 'price' => 590, 'unit_id' => 'Pcs',
            'name' => 'HDP Bend - 110mm-local', 'price' => 120, 'unit_id' => 'Pcs',
            'name' => 'HDP Bend - 110mm-45*-local', 'price' => 120, 'unit_id' => 'Pcs',
            'name' => 'HDP Soket - 110mm-Local', 'price' => 65, 'unit_id' => 'Pcs',
            'name' => 'Sink 16*18 - Snow', 'price' => 2250, 'unit_id' => 'Pcs/n',
            'name' => 'Sink 16*18 - Image', 'price' => 2800, 'unit_id' => 'Pcs/n',
            'name' => 'Water Pump-1HP (SSW-100)-Sporty', 'price' => 22200, 'unit_id' => 'Pcs',
            'name' => 'Tiles 16*16 Nepovit-AtlasTreviso (6p)', 'price' => 88, 'unit_id' => 'Sqr/n',
            'name' => 'Tiles 16*16 Nepovit- MarmoWood (6p)', 'price' => 88, 'unit_id' => 'Sqr/n',
            'name' => 'Water Pump Mud 3"" (Laltin) -1HP - CH', 'price' => 13500, 'unit_id' => 'Pcs/n',
            'name' => 'Agricultural Pipe 3""', 'price' => 500, 'unit_id' => 'Kg/n',
            'name' => 'Wash Basin & Pedstal-414 -Jenson', 'price' => 6300, 'unit_id' => 'Set/n',
            'name' => 'Pillar Cock-R', 'price' => 500, 'unit_id' => 'Set/n',
            'name' => 'Hanging Clamp - 110mm', 'price' => 240, 'unit_id' => 'Pcs/n',
            'name' => 'Hanging Clamp - 75mm', 'price' => 170, 'unit_id' => 'Pcs/n',
            'name' => '26352IN-M-NA (Conceled Cistern)', 'price' => 18471, 'unit_id' => 'Set',
            'name' => 'Ppr F.Tee 20mm', 'price' => 215, 'unit_id' => 'Pcs',
            'name' => 'Latex Shield 2K - 3Kg', 'price' => 1225, 'unit_id' => 'Pkt',
            'name' => 'Jacuzzi With Air Bubble Spa - Hylux', 'price' => 385000, 'unit_id' => 'Set',
            'name' => 'Concealed Stop Cock - SLK', 'price' => 2880, 'unit_id' => 'Pcs',
            'name' => 'Vegaquick - 50gm', 'price' => 215, 'unit_id' => 'Pcs/n',
            'name' => 'Vegaquick - 20gm', 'price' => 95, 'unit_id' => 'Pcs/n',
            'name' => 'Gi Union 1.1/2""', 'price' => 1045, 'unit_id' => 'Pcs',
            'name' => 'Gi elbow 1.1/2""', 'price' => 555, 'unit_id' => 'Pcs',
            'name' => 'Gi Long Nipple 1.1/2*4""', 'price' => 200, 'unit_id' => 'Pcs',
            'name' => 'Gi R.Soket 2*1.1/2""', 'price' => 628, 'unit_id' => 'Pcs',
            'name' => 'HDP Pipe-NS-PN16 - 32mm', 'price' => 101.06, 'unit_id' => 'Mtr',
            'name' => 'CP Head', 'price' => 380, 'unit_id' => 'Pcs/n',
            'name' => 'Tiles 24*24 Prime-Trepcana Rose (4p)', 'price' => 145, 'unit_id' => 'Sqr/n',
            'name' => 'Rangoli Total Cear 10ltr', 'price' => 4250, 'unit_id' => 'Pcs/n',
            'name' => 'Rangoli Total Cear 4ltr', 'price' => 2020, 'unit_id' => 'Pcs/n',
            'name' => 'Rangoli Total Cear 1ltr', 'price' => 510, 'unit_id' => 'Pcs/n',
            'name' => 'Cpvc R.Elbow - 1*3/4""', 'price' => 161, 'unit_id' => 'Pcs',
            'name' => 'Tiles 12*18 Ext. Titan-11 (5p)', 'price' => 125, 'unit_id' => 'Sqr/n',
            'name' => 'City Pan - Stalo', 'price' => 1250, 'unit_id' => 'Set/n',
            'name' => 'City Pan - Terovit', 'price' => 1900, 'unit_id' => 'Set/n',
            'name' => 'Sink Mixer -Praseo-T1335A1', 'price' => 8080, 'unit_id' => 'Set',
            'name' => 'Wash Basin Glory -C041C-530*410', 'price' => 4180, 'unit_id' => 'Pcs',
            'name' => 'Pedestal Long Glory -C0383', 'price' => 4060, 'unit_id' => 'Pcs',
            'name' => 'Water Pump Submercial/4""-1.5HP (15stg) ', 'price' => 20400, 'unit_id' => 'Set/n',
            'name' => 'Sink Mixer S/L (T/M) - Aqua - G571GA1', 'price' => 8520, 'unit_id' => 'Set',
            'name' => 'Wash Basin Kolar -530*380-C042P', 'price' => 3750, 'unit_id' => 'Pcs',
            'name' => 'Wash Basin NovalPlus -(550*395) -C042N', 'price' => 4080, 'unit_id' => 'Pcs',
            'name' => 'Pedestal Long Noval - C0324', 'price' => 3240, 'unit_id' => 'Pcs',
            'name' => 'Gi Pluge 3/4""', 'price' => 138, 'unit_id' => 'Pcs',
            'name' => 'Urinal Auto Closing Valve - G2007A1', 'price' => 4390, 'unit_id' => 'Pcs',
            'name' => 'Wall Mixer 2/1 Quattro - T2316A1', 'price' => 15030, 'unit_id' => 'Set',
            'name' => 'Glass Self - ABS Corner', 'price' => 950, 'unit_id' => 'Pcs/n',
            'name' => 'Silicone (Resibond) GP-100 - 240ml', 'price' => 476, 'unit_id' => 'Pcs/n',
            'name' => 'Water Pump-0.5HP (CutePlus) - KSB', 'price' => 7960, 'unit_id' => 'Pcs',
            'name' => 'Commod Spray - Cinder', 'price' => 1640, 'unit_id' => 'Set/n',
            'name' => 'Upset - Lide', 'price' => 380, 'unit_id' => 'Pcs/n',
            'name' => 'Cistern Fitting Pvc D/F', 'price' => 750, 'unit_id' => 'Set/n',
            'name' => 'Gi Long Nipple 1/2*3""', 'price' => 60, 'unit_id' => 'Pcs',
            'name' => 'Tiles 24*48 NeMato-OracleGold (2p)', 'price' => 162, 'unit_id' => 'Sqr/n',
            'name' => 'Tanki Birko - Normal', 'price' => 300, 'unit_id' => 'Pcs/n',
            'name' => 'Ppr R.Elbow 32*25mm', 'price' => 77, 'unit_id' => 'Pcs',
            'name' => 'Water Pump-1HP (Classic-10) - Supertake', 'price' => 9700, 'unit_id' => 'Pcs',
            'name' => 'Pvc Anglevalve', 'price' => 250, 'unit_id' => 'Pcs/n',
            'name' => 'Masking Tape', 'price' => 45, 'unit_id' => 'Pcs/n',
        ];

        DB::table('items')->insert($items);
    }
}
